### ISSUE TITLE
Unlocking unlocked lock

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix#1005]
From Coverity analysis:
```
*** CID 168766:  API usage errors  (LOCK)
/src/mca/common/dstore/dstore_base.c: 2264 in _dstore_fetch()
2258         }
2259         rc = PMIX_ERR_NOT_FOUND;
2260         return rc;
2261     
2262     error:
2263         if (lock_is_set) {
   CID 168766:  API usage errors  (LOCK)
   "pthread_mutex_unlock" unlocks "ds_ctx->lock" while it is unlocked.
2264             pthread_mutex_unlock(&ds_ctx->lock);
2265         }
2266         PMIX_ERROR_LOG(rc);
2267         return rc;
2268     }
2269     
```

@artpol84 @karasevb Can you please take a look?

**Comment by rhc54** [comment]
There are also a number of other defects reported in the test directory. I tried to fix them, but then Jenkins wouldn't pass, so I'm not sure of the correct way to resolve them. Could you please take a look?

**Comment by rhc54** [comment]
I believe you both have Coverity access: https://scan4.coverity.com/reports.htm#v14495/p10520

**Comment by artpol84** [comment]
Thanks, we will take care.
