### ISSUE TITLE
REGRESSION: 3.1.0rc2 fails on 32-bit archs

### ISSUE THREAD

**Issue by amckinstry** [pmix/pmix#1032]
This is testing within Debian.

3.1.0rc1 works fine; 3.1.0rc2 fails on 32-bit archs.

See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918157

This is with openmpi 3.1.3.  This will not compile as it stands with rc2 (rc1 was fine), so there was a patch needed:
https://salsa.debian.org/hpc-team/openmpi/blob/debian/master/debian/patches/pmix-modex.patch

Which would be instantly suspect, except the combination works with 64-bit archs (arm64, amd, etc).

The problem is easily reproduced with a simple MPI code on i386:

```
/*
  sudo apt-get install mpi-default-bin mpi-default-dev
  export OMPI_MCA_plm_rsh_agent=/bin/false
  export OMPI_MCA_rmaps_base_oversubscribe=1
  mpicc -o mpi-test mpi-test.c && mpirun -np 2 ./mpi-test
*/
#include <mpi.h>
int main(int argc, char** argv)
{
  MPI_Init(&argc, &argv);
  MPI_Finalize();
  return 0;
}
```

giving:
```
export OMPI_MCA_orte_base_help_aggregate=0
export OMPI_MCA_btl_base_verbose=100
alastair@debian32:~$ mpirun -n 2 -mca btl self ./a.out
[debian32:04634] mca: base: components_register: registering framework btl components
[debian32:04634] mca: base: components_register: found loaded component self
[debian32:04634] mca: base: components_register: component self register function successful
[debian32:04634] mca: base: components_open: opening btl components
[debian32:04634] mca: base: components_open: found loaded component self
[debian32:04634] mca: base: components_open: component self open function successful
[debian32:04634] select: initializing btl component self
[debian32:04634] select: init of component self returned success
[debian32:04635] mca: base: components_register: registering framework btl components
[debian32:04635] mca: base: components_register: found loaded component self
[debian32:04635] mca: base: components_register: component self register function successful
[debian32:04635] mca: base: components_open: opening btl components
[debian32:04635] mca: base: components_open: found loaded component self
[debian32:04635] mca: base: components_open: component self open function successful
[debian32:04635] select: initializing btl component self
[debian32:04635] select: init of component self returned success
[debian32:04634] mca: bml: Using self btl for send to [[38777,1],0] on node debian32
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[38777,1],0]) is on host: debian32
  Process 2 ([[38777,1],1]) is on host: debian32
  BTLs attempted: self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
MPI_INIT has failed because at least one MPI process is unreachable
from another.  This *usually* means that an underlying communication
plugin -- such as a BTL or an MTL -- has either not loaded or not
allowed itself to be used.  Your MPI job will now abort.

You may wish to try to narrow down the problem;

 * Check the output of ompi_info to see which BTL/MTL plugins are
   available.
 * Run your application with MPI_THREAD_SINGLE.
 * Set the MCA parameter btl_base_verbose to 100 (or mtl_base_verbose,
   if using MTL-based communications) to see exactly which
   communication plugins were considered and/or discarded.
--------------------------------------------------------------------------
[debian32:04634] *** An error occurred in MPI_Init
[debian32:04634] *** reported by process [2541289473,0]
[debian32:04634] *** on a NULL communicator
[debian32:04634] *** Unknown error
[debian32:04634] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[debian32:04634] ***    and potentially your MPI job)
[debian32:04635] mca: bml: Using self btl for send to [[38777,1],1] on node debian32
--------------------------------------------------------------------------
At least one pair of MPI processes are unable to reach each other for
MPI communications.  This means that no Open MPI device has indicated
that it can be used to communicate between these processes.  This is
an error; Open MPI requires that all MPI processes be able to reach
each other.  This error can sometimes be the result of forgetting to
specify the "self" BTL.

  Process 1 ([[38777,1],1]) is on host: debian32
  Process 2 ([[38777,1],0]) is on host: debian32
  BTLs attempted: self

Your MPI job is now going to abort; sorry.
--------------------------------------------------------------------------
[debian32:04629] PMIX ERROR: UNREACHABLE in file ../../../src/server/pmix_server.c at line 2091
```

**Comment by rhc54** [comment]
I'm unsure if this is a PMIx problem or an issue in the OMPI glue code - certainly, the change you cite to get it to compile is one required over there. As we've stated, the PMIx v3.1.0 release will be fully compliant with the v3 standard. The pmix_info_array_t data type was deprecated in v2 of the standard and subsequently removed in v3 - hence it has been removed from v3.1.0rc2 as we continue to move towards compliance.

I'll duplicate the issue over there and reference this one in case they eventually identify something in PMIx itself that needs adjustment.

**Comment by ggouaillardet** [comment]
`mpirun -n 2 -mca btl self ./a.out` is unlikely to work.
If `pml/ob1` is used, then it will always fail. It can only work if an other `pml` is used, and that typically happen when some specifically hardware/software is available (typically OmniPath or UCX) and `btl/self` is not used in that case.

I have some hard time understanding the patch.
One patch is for the embedded PMIx, and the other is for external PMIx 1.x.
At first glance, I do not understand why the former is required. The `pmix/ext1x` component should not even be built if external PMIx 3.1.0 is used, so I do not see how the latter is required. Can you please clarify how you build/test Open MPI / PMIx ?

**Comment by rhc54** [comment]
Minus the removed pmix_info_array_t, it should actually work. All that would be required is to adjust the ext2x component so it doesn't reference that datatype. However, so far as I know, that (PMIx v3.x with OMPI v3.x) is a configuration OMPI doesn't support.

**Comment by amckinstry** [comment]
If I run the code with `mpirun -n 2 ./a.out` I get:
```
[debian32:00774] *** An error occurred in MPI_Init
[debian32:00774] *** reported by process [2274492417,1]
[debian32:00774] *** on a NULL communicator
[debian32:00774] *** Unknown error
[debian32:00774] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[debian32:00774] ***    and potentially your MPI job)
```

So, no line reporting where the error is, but still an error.

The patch is a bit of a hack to get openmpi 3.1.3 compiling with pmix 3.1.0rc2 (I'm not expecting these to be the versions to ship in Debian 10, but wanted to shake out any errors ASAP, and so test rc2). The two patch parts just make sure the code will compile without PMIX_MODEX and PMIX_INFO_ARRAY defined.

**Comment by amckinstry** [comment]
Thanks @ggouaillardet that appears to be working ok here. My simple tests worked, testing via CI now.

**Comment by rhc54** [comment]
This is now in both PMIx master and v3.1.0 branch, and associated changes in OMPI master have been made. The PR into OMPI v3.x has been accepted and should be in the next release there.
