### ISSUE TITLE
undefined symbol pmix_cb_t_class

### ISSUE THREAD

**Issue by Zwilla** [pmix/pmix#1033]
Error: pmix_mca_base_component_repository_open: unable to open mca_gds_ds21: /usr/local/lib/libmca_common_dstore.so.0: undefined symbol: pmix_cb_t_class (ignored)

OS: Ubuntu

**Comment by rhc54** [comment]
Could you please tell us what version of PMIx you are using?

**Comment by Zwilla** [comment]
Hi, sure I was using master

**Comment by rhc54** [comment]
Check to see if you might have installed on top of a preexisting installation. Looking at the code, I see no way that error could be correct. I'd blow away your installation, re-clone master, and rebuild.

**Comment by rhc54** [comment]
Please reopen if it persists.
