### ISSUE TITLE
prun crashes with PMIx v3.1

### ISSUE THREAD

**Issue by ggouaillardet** [pmix/pmix#1042]
from the latest `prrte/master` and `pmix/v3.1` branches, `prun` crashes
because `pmix_server_globals.system_tmpdir` is `NULL`.

fwiw, the patch below is good enough, though I am not sure this is the right fix.

```patch
diff --git a/src/mca/ptl/tcp/ptl_tcp_component.c b/src/mca/ptl/tcp/ptl_tcp_component.c
index cfc0ac6..68e2928 100644
--- a/src/mca/ptl/tcp/ptl_tcp_component.c
+++ b/src/mca/ptl/tcp/ptl_tcp_component.c
@@ -13,8 +13,8 @@
  * Copyright (c) 2015      Los Alamos National Security, LLC. All rights
  *                         reserved.
  * Copyright (c) 2016-2019 Intel, Inc.  All rights reserved.
- * Copyright (c) 2017-2018 Research Organization for Information Science
- *                         and Technology (RIST). All rights reserved.
+ * Copyright (c) 2017-2019 Research Organization for Information Science
+ *                         and Technology (RIST).  All rights reserved.
  * Copyright (c) 2018      IBM Corporation.  All rights reserved.
  * $COPYRIGHT$
  *
@@ -265,7 +265,11 @@ static pmix_status_t component_open(void)
 
     if (PMIX_PROC_IS_SERVER(pmix_globals.mypeer) ||
         PMIX_PROC_IS_LAUNCHER(pmix_globals.mypeer)) {
-        mca_ptl_tcp_component.system_tmpdir = strdup(pmix_server_globals.system_tmpdir);
+        if (NULL != pmix_server_globals.system_tmpdir) {
+            mca_ptl_tcp_component.system_tmpdir = strdup(pmix_server_globals.system_tmpdir);
+        } else {
+            mca_ptl_tcp_component.system_tmpdir = strdup(mca_ptl_tcp_component.session_tmpdir);
+        }
     } else {
         if (NULL != (tdir = getenv("PMIX_SYSTEM_TMPDIR"))) {
             mca_ptl_tcp_component.system_tmpdir = strdup(tdir);

```

**Comment by rhc54** [comment]
I saw this too, but haven't had a chance to look at it yet. I suspect that is the correct answer, but I'm puzzled as to how the system_tmpdir is NULL. Let me take a gander and see what's going on and why master doesn't have it.

**Comment by rhc54** [comment]
I found it - the pmix_tool.c code is out-of-date. I'll update it and check for any other lagging code.

**Comment by rhc54** [comment]
Wow - there's a bunch of files that are out-of-date. Guess cherry-picking missed quite a few commits somewhere. I'll do an update and reissue the RC.

**Comment by ggouaillardet** [comment]
I confirm this issue is fixed in `rc4` :-)

I found a memory leak with `prun -n 1 ./hello` (from the `examples` directory of `pmix`.
I did not test `master` but since this is not a missing cherry-pick, `master` might leak too ...

The patch below fixes it

```patch
diff --git a/src/event/pmix_event_notification.c b/src/event/pmix_event_notification.c
index 093023b..61d257a 100644
--- a/src/event/pmix_event_notification.c
+++ b/src/event/pmix_event_notification.c
@@ -1002,6 +1002,7 @@ static void _notify_client_event(int sd, short args, void *cbdata)
                                  * from the cache */
                                 if (0 == cd->nleft) {
                                     pmix_hotel_checkout(&pmix_globals.notifications, cd->room);
+                                    PMIX_RELEASE(cd);
                                 }
                                 break;
                             }
```

**Comment by rhc54** [comment]
Kewl - I left the tarballs as they are and we'll just pick things like this up as we go. Would you file a PR against master (if needed) and then I'll cherry-pick it to v3.1?

**Comment by ggouaillardet** [comment]
yep, I will do that.

**Comment by rhc54** [comment]
Are we ready to close this? I think v3.1 is ready to go - at this point, I'm thinking I'd update the OMPI PR and ask that they merge it for MTT exposure, then wait a week to see how that does before officially releasing. Make sense?

**Comment by ggouaillardet** [comment]
yep, let's close this !
