### ISSUE TITLE
PMIx_generate_regex may not preserve ordering

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix#1049]
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

`v2.2rc2` (it doesn't look like this changed much on `master`) tarball

-----------------------------

## Details of the problem

A PMIx server must use `PMIx_generate_regex` to generate the string value to pass for `PMIX_NODE_MAP`, and pair it with `PMIx_generate_ppn` to generate the string for `PMIX_PROC_MAP`. The ordering of these two maps provide PMIx with the node-to-rank mapping of the job.

On the client side these two keys are the backing for `PMIx_Resolve_nodes` and `PMIx_Resolve_peers` which provide access to this mapping.

If the hostnames contain more than one block of digits (e.g., `a28n03`) then the ordering is not preserved. This leads to an incorrect node-to-rank mapping being exposed to the client. If there is only one block of numbers then it seems to work ok.

#### Test program
```c
#define _GNU_SOURCE
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>

#include <pmix.h>
#include <pmix_server.h>

static pmix_proc_t myproc;

int main(int argc, char **argv)
{
    int rc;
    char *regex = NULL, *input;

    if (PMIX_SUCCESS != (rc = PMIx_Init(&myproc, NULL, 0))) {
        fprintf(stderr, "Client %s:%d PMIx_Init failed: %d\n", myproc.nspace, myproc.rank, rc);
        exit(0);
    }

    input = strdup("a28n01,a28n02,a28n03,a28n04,a29n01,a29n02,a29n03");
    PMIx_generate_regex(input, &regex);

    printf("INPUT: %s\n", input);
    printf("REGEX: %s\n\n", regex);
    free(regex); free(input);

    input = strdup("a28n01,a29n02,a28n03,a28n04,a29n01,a28n02,a29n03");
    //                     ------                      ------
    PMIx_generate_regex(input, &regex);

    printf("INPUT: %s\n", input);
    printf("REGEX: %s\n\n", regex);
    free(regex); free(input);

    input = strdup("a2801,a2901,a2802,a2902,a2804,a2903");
    PMIx_generate_regex(input, &regex);

    printf("INPUT: %s\n", input);
    printf("REGEX: %s\n", regex);
    free(regex); free(input);


    if (PMIX_SUCCESS != (rc = PMIx_Finalize(NULL, 0))) {
        fprintf(stderr, "Client %s:%d PMIx_Finalize failed: %d\n", myproc.nspace, myproc.rank, rc);
    }

    fflush(stderr);
    return(0);
}
```

#### Example output

```shell
shell$ prun -np 1 ./pmix_node_regex
INPUT: a28n01,a28n02,a28n03,a28n04,a29n01,a29n02,a29n03
REGEX: pmix[a[2:28-29]n01,a[2:28-29]n02,a[2:28-29]n03,a[2:28]n04]

INPUT: a28n01,a29n02,a28n03,a28n04,a29n01,a28n02,a29n03
REGEX: pmix[a[2:28-29]n01,a[2:29,28]n02,a[2:28-29]n03,a[2:28]n04]

INPUT: a2801,a2901,a2802,a2902,a2804,a2903
REGEX: pmix[a[4:2801,2901,2802,2902,2804,2903]]
```

**Comment by rhc54** [comment]
FWIW: quick check of my email archive shows that ORTE was getting close to 10x compression on the launch message string using zlib (that was dated 10 years ago!). There was a note that lzo (https://www.oberhumer.com/opensource/lzo/) did better, but I haven't verified it. Note that lzo is GPL so we need to be careful if you decide to use it.

Given that we are looking specifically at node names, and those will have some kind of repeating pattern, you might consider using lex, of something like http://re2c.org/, or just the generally available POSIX library (https://www.gnu.org/software/libc/manual/html_node/POSIX-Regexp-Compilation.html#POSIX-Regexp-Compilation). I would vote for the latter - we could just circulate the regex struct as part of the host's wireup protocol for the servers.

**Comment by jjhursey** [comment]
Yeah we could use the `pmix_util_compress_string` and `pmix_util_uncompress_string` functions.

That would be a neat feature to investigate, but we would need a different attribute to pass it along so we knew how to parse it properly.

**Comment by rhc54** [comment]
Just prefix the result with something like "zlib" instead of "pmix", and then adjust the code to recognize it so we know to use those utils instead of the regex functions. Or we could go the true glory road and create a new regex framework 😄

**Comment by jjhursey** [comment]
The problem with adding a new prefix is the cross version issue. If the client is running an older version that doesn't recognize the `zlib` prefix, then it'll fail. If it's a new component to the regex framework then I think that would work since we should be negotiating the selection of the component during the handshake (right?).
