### ISSUE TITLE
PMIX_NUM_SLOTS not defined in v3.1.2

### ISSUE THREAD

**Issue by krempel-pt** [pmix/pmix#1092]
This is about PMIx v3.1.2 which should be fully compliant to PMIx Standard v3.0.

PMIX_NUM_SLOTS described in PMIx Standard v3.0 on page 63 line 27 is not defined in pmix_common.h.

Nor can it be found anywhere else in the source code, so i guess the equivalence to PMIX_UNIV_SIZE described on page 224 in line 16 of the Standard is not yet given.

**Comment by rhc54** [comment]
Correct - PMIX_NUM_SLOTS was removed in PMIx Standard v3.1(draft) as it is duplicative to PMIX_UNIV_SIZE. However, I should have noted it in the "history" section - I will update the draft to do so.

**Comment by rhc54** [comment]
Updated history:
```
remove PMIX_NUM_SLOTS as it is duplicative of (a) PMIX_UNIV_SIZE when used at the
session level and (b) PMIX_MAX_PROCS when used at the job and application levels
```
Thanks!
