### ISSUE TITLE
Generalize `bfrops` components

### ISSUE THREAD

**Issue by karasevb** [pmix/pmix#1099]
According to Issue #681, I'm working on the implementation of new flexible packing with a new component `bfrops`.
My question is to avoid duplication of code and simplify future bfrops multi-component support.

**Details:**
I forked bfrops v3 to v4 and modified it for use new flexible packing by changing pack/unpack registration functions. We want to use new pack/unpack functions for all integer types. For integer-based PMIx types (like `PMIX_INT16`, `PMIX_INT32`, `PMIX_SIZE` etc) is not a problem to replace registration functions to new:
```C
    PMIX_REGISTER_TYPE("PMIX_SIZE", PMIX_SIZE,
                       pmix4_bfrops_base_pack_int_flex, <- replaced
                       pmix4_bfrops_base_unpack_int_flex, <-replaced
                       ...
                       &mca_bfrops_v4_component.types);
```
The complex PMIx types, such as `PMIX_DATA_ARRAY`, `PMIX_KVAL`, etc., directly call into its implementation a simple-integer packing functions. 
Let's consider a packing for `PMIX_DATA_ARRAY`:
```C
    PMIX_REGISTER_TYPE("PMIX_DATA_ARRAY", PMIX_DATA_ARRAY,
                       pmix_bfrops_base_pack_darray,
                       pmix_bfrops_base_unpack_darray,
                       ...
```
The function `pmix_bfrops_base_pack_darray` uses `pmix_bfrops_base_pack_int64` direclty:
https://github.com/pmix/pmix/blob/0f7075f7d204b3cf46ef2aa43120632696cd858a/src/mca/bfrops/base/bfrop_base_pack.c#L883

**The issue is in following:** to implement the new bfrops component, that has foreign simple-packing integer methods it requires a full duplicate of implementation of complex-packing PMIx types. For example: for `pmix_bfrops_base_pack_darray` will require to call new `pmix_bfrops_base_pack_int64`, that require a duplicate of `pmix_bfrops_base_pack_darray` with new int64 packing. 

The multiple duplications is not a right way. So I would like to propose another way, that requires to modify a prototype of pack/unpack methods by adding `pmix_pointer_array_t *regtypes` to each one.
Example of `pmix_bfrops_base_pack_darray` modification:
```patch
 pmix_status_t pmix_bfrops_base_pack_darray(pmix_buffer_t *buffer, const void *src,
-                                           int32_t num_vals, pmix_data_type_t type)
+                                           int32_t num_vals, pmix_data_type_t type,
+                                           pmix_pointer_array_t *regtypes)
 {
     pmix_data_array_t *p = (pmix_data_array_t*)src;
     pmix_status_t ret;
     int32_t i;
+    pmix_bfrop_type_info_t *info;
 
     for (i=0; i < num_vals; i++) {
+        /* Lookup the pack function for this type and call it */
+        if (NULL == (info = (pmix_bfrop_type_info_t*)pmix_pointer_array_get_item(regtypes, type))) {
+            PMIX_ERROR_LOG(PMIX_ERR_UNKNOWN_DATA_TYPE);
+            return PMIX_ERR_UNKNOWN_DATA_TYPE;
+        }
         /* pack the actual type in the array */
         if (PMIX_SUCCESS != (ret = pmix_bfrop_store_data_type(buffer, p[i].type))) {
             return ret;
@@ -805,190 +812,10 @@ pmix_status_t pmix_bfrops_base_pack_darray(pmix_buffer_t *buffer, const void *sr
             /* nothing left to do */
             continue;
         }
-        /* pack the actual elements - have to do this the hard way */
-        switch(p[i].type) {
-            case PMIX_UNDEF:
-                break;
-            case PMIX_BOOL:
-                if (PMIX_SUCCESS != (ret = pmix_bfrops_base_pack_bool(buffer, p[i].array, p[i].size, PMIX_BOOL))) {
-                    return ret;
-                }
-                break;
-            case PMIX_BYTE:
-            case PMIX_STRING:
-            case PMIX_STRING:
-                if (PMIX_SUCCESS != (ret = pmix_bfrops_base_pack_string(buffer, p[i].array, p[i].size, PMIX_STRING))) {
-                    return ret;
-                }
-                break;
-            case PMIX_SIZE:
-            case PMIX_PID:
-            case PMIX_INT:
...
-            case PMIX_ENVAR:
-                if (PMIX_SUCCESS != (ret = pmix_bfrops_base_pack_envar(buffer, p[i].array, p[i].size, PMIX_ENVAR))) {
-                    return ret;
-                }
-                break;
-
-            default:
-                pmix_output(0, "PACK-PMIX-VALUE[%s:%d]: UNSUPPORTED TYPE %d",
-                            __FILE__, __LINE__, (int)p[i].type);
-            return PMIX_ERROR;
+        ret = info->odti_pack_fn(buffer, p[i].array, p[i].size, p[i].type);
+        if (PMIX_SUCCESS != ret) {
+            PMIX_ERROR_LOG(ret);
+            return ret;
         }
     }
     return PMIX_SUCCESS;

```
` *regtypes` must be passed from the upper abstract level of pack/unpack functions, also should be updated pack/unpack methods for all existed bfrops. 

This way allows keeping a common `pmix_bfrops_base_pack_darray` in base-code, and `odti_pack_fn` will call a specific registered packing method, that can be different between the version of bfrops. This allows reducing of code duplication, and simplify the support. The likewise modification is required other comlex-packing types.

**Comment by karasevb** [comment]
@rhc54 @artpol84 
Do you have any objections/suggestion?

**Comment by rhc54** [comment]
Looks like a really good way of doing it so long as the result remains unchanged.

**Comment by artpol84** [comment]
It looks good to me as well. 
Let's implement this.
To decouple this change from the flexible packing thing I suggest to implement this infrastructure change first in a separate commit and create a bfrops 4 as a subsequent one.

**Comment by karasevb** [comment]
Refs https://github.com/pmix/pmix/pull/1126

**Comment by artpol84** [comment]
@karasevb Lets re-open this one and update it properly
