### ISSUE TITLE
unable to build with --enable-embedded-libevent

### ISSUE THREAD

**Issue by raffenet** [pmix/pmix#1100]
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @ f752b0f62cba1135bf55336c2d53305523fa5dea

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version: Ubuntu 16.04.5 LTS
* Computer hardware: Intel Xeon 6130
* Network type: Ethernet

-----------------------------

## Details of the problem

My system does not have a libevent development package installed. I tried adding `--enable-embedded-libevent` to my configure (config.log attached), but met the following error at make time.

```
Making all in mca/bfrops
make[2]: Entering directory '/sandbox/raffenet/pmix/src/mca/bfrops'
  CC       base/bfrop_base_frame.lo
In file included from /sandbox/raffenet/pmix/src/include/pmix_globals.h:26:0,
                 from /sandbox/raffenet/pmix/src/mca/bfrops/base/base.h:40,
                 from base/bfrop_base_frame.c:39:
/sandbox/raffenet/pmix/src/include/types.h:45:27: fatal error: event.h: No such file or directory
compilation terminated.
Makefile:728: recipe for target 'base/bfrop_base_frame.lo' failed
make[2]: *** [base/bfrop_base_frame.lo] Error 1
make[2]: Leaving directory '/sandbox/raffenet/pmix/src/mca/bfrops'
Makefile:1864: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/sandbox/raffenet/pmix/src'
Makefile:748: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

```
[config.log](https://github.com/pmix/pmix/files/2838101/config.log)

**Comment by rhc54** [comment]
There is no embedded libevent in the PMIx library - it requires that there be an external one installed on the system. Ditto for hwloc, for that matter.

**Comment by raffenet** [comment]
OK. It's easy enough to build libevent on my own and point PMIx at it. However, my first instinct to look in `./configure --help` led me to believe there was an embedded one. https://github.com/pmix/pmix/blob/master/config/pmix_setup_libevent.m4#L22

**Comment by rhc54** [comment]
I see where the confusion comes from - there are flags for support of OMPI's embedded libevent and hwloc. Let me see if we can find another name for those flags or maybe another way of supporting them.

**Comment by rhc54** [comment]
I have removed those flags - thanks for bringing them to my attention!
