### ISSUE TITLE
PMIX_NUMERIC_VERSION semantic

### ISSUE THREAD

**Issue by ggouaillardet** [pmix/pmix#1101]
What is the definition of `PMIX_NUMERIC_VERSION` ?

Is this related to the version of the PMIx standard ?
Or is this related to the version of the current release (e.g. `(PMIX_VERSION_MAJOR<<16) | (PMIX_VERSION_MINOR<<8) | PMIX_VERSION_RELEASE)` ?

In the latter case, `PMIX_NUMERIC_VERSION` is not correctly set in some releases (such as `3.1.2`) and I can have it autogenerated by `configure`.

**Comment by rhc54** [comment]
It should be the latter - I know I missed updating the last digit in some cases. Having it autogenerated would be a good thing and much appreciated (I just haven't had time to do so).

**Comment by ggouaillardet** [comment]
PR were merged into `master` and all release branches >= 2.2
