### ISSUE TITLE
"mca_pcompress_zlib" does not appear to be a valid pcompress MCA dynamic component

### ISSUE THREAD

**Issue by tonycurtis** [pmix/pmix#1147]
Thank you for taking the time to submit an issue!

## Background information

Just updated PMIx with git-pull, getting warning messages

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @ 41eae968a78b7dbd7b460390a00b670eb30db4e3

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware:  x86_64
* Network type: IB

-----------------------------

## Details of the problem

Get this kind of message from both `prte` and `prun` (first noticed in client)

```sh
[login2:68289] pmix_mca_base_component_repository_open: "mca_pcompress_zlib" does not appear to be a valid pcompress MCA dynamic component (ignored): /gpfs/projects/ChapmanGroup/opt/pmix/git/lib/pmix/mca_pcompress_zlib.so: undefined symbol: mca_pcompress_zlib_component. ret -1
```

The `mca_pcompress_zlib_component` symbol is in the .so file, but `nm` shows it as local ("d").

PMIx configure says

```sh
+++ Configuring MCA framework pcompress
checking for no configure components in framework pcompress...
checking for m4 configure components in framework pcompress... zlib

--- MCA component pcompress:zlib (m4 configuration macro)
checking for MCA component pcompress:zlib compile mode... dso
checking for zlib in... (default search paths)
looking for header without includes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
looking for library without search path
checking for library containing deflate... -lz
checking will zlib support be built... yes
checking if MCA component pcompress:zlib can compile... yes
```

**Comment by rhc54** [comment]
Looks like a missing visibility declaration - see https://github.com/pmix/pmix/pull/1148
