### ISSUE TITLE
PMIx_Get of local process rank data failing

### ISSUE THREAD

**Issue by dsolt** [pmix/pmix#1172]
Thank you for taking the time to submit an issue!

## Background information

This issue is similar to issue 1168 but is not the same.   In that case if I set
 export PMIX_MCA_gds=hash 
the problem goes away, but this problem is slightly different.  See below for details.
That ticket is about when the rank is PMIX_RANK_WILDCARD, but this issue is about 
using specific ranks.

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
3.1

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
git clone

### Please describe the system on which you are running

* Operating system/version: Linux
* Computer hardware: IBM Power
* Network type: TCP

-----------------------------

## Details of the problem

In this case I am trying to do:
proc.rank = 0;
strcpy(proc.nspace, argv[1]);
rc = PMIx_Get(&proc, PMIX_HOSTNAME, NULL, 0, &val);

In this case proc is known to be a running on the local node. (when it is not I see a call to server_dmodex_req coming up to the server).  The PMIx_Get call hangs, but no server_dmodex_req call is coming up to the server.   If I do the same get call on the process itself, it works ok and even if I do it on another rank in the same namespace running locally, but when it is a different namespace and a specific rank (not PMIX_RANK_WILDCARD), then it hangs.  

I can reproduce this using PMIx_Spawn under mpirun/orted as well.

**Comment by rhc54** [comment]
Just to be clear: since proc is running on the local node, can we assume that the server called register_nspace on that namespace prior to the issuing of PMIx_Get?

**Comment by dsolt** [comment]
Yes... and processes in that namespace seem to be able to get their own PMIX_HOSTNAME values

**Comment by dsolt** [comment]
I'm going to try to writeup a full reproducer that can be run under mpirun/orted  just to make sure I'm not doing something wrong under my launcher :)

**Comment by dsolt** [comment]
Ok, this code hangs for me with mpirun as well as jsrun, so I suspect it is a problem in the CL.  I also run with PMIX_MCA_gds=hash and it does not change behavior.

```
#include <stdlib.h>
#include <stdio.h>
#include <pmix.h>

int main(int argc, char *argv[]) {

  pmix_proc_t proc, myproc;
  char child_nspace[PMIX_MAX_NSLEN];
  char cwd[1024];
  pmix_value_t *val1, *val2;
  int rc;

  pmix_app_t app;

  rc = PMIx_Init(&myproc, NULL, 0);

  app.cmd = strdup("/bin/sleep");
  app.argv = (char**) malloc(sizeof(char*) * 3);
  app.argv[0] = strdup("/bin/sleep");
  app.argv[1] = strdup("60");
  app.argv[2] = NULL;
  app.env = NULL;
  app.cwd = getcwd(cwd, 1024);
  app.maxprocs = 1;
  app.info = NULL;
  app.ninfo = 0;

  PMIx_Spawn(NULL, 0, &app, 1, child_nspace);

 fprintf(stderr, "Created a child with nspace name '%s'\n", child_nspace);

  strcpy(proc.nspace, child_nspace);
  proc.rank = 0;   // hangs

  rc = PMIx_Get(&myproc, PMIX_HOSTNAME, NULL, 0, &val1);
  fprintf(stderr, "rc of my proc HOSTNAME: %d with value %s\n", rc, (rc ? "" : val1->data.string));

  rc = PMIx_Get(&proc, PMIX_HOSTNAME, NULL, 0, &val2);
  fprintf(stderr, "rc of CHILD proc HOSTNAME: %d with value %s\n", rc, (rc ? "" : val2->data.string));

  PMIx_Finalize(NULL, 0);
}
```

**Comment by rhc54** [comment]
I confirm it behaves the same with PRRTE as well - I'm looking into it. I plan to fix the hang first and then see why the info isn't being found.

**Comment by rhc54** [comment]
Just an update. I almost have this fixed now. The "hang" wasn't actually hanging - the problem was that the code assumed that the child job would also be calling PMIx_Init and therefore was waiting for that to happen before responding. Since the child in this case was ```sleep```, it never met that condition. The child job would eventually complete and everything exits (assuming you waited long enough).

I updated the code to allow the ```get``` to proceed (without waiting for the child job to connect to the server) if the request was for job-level info - which then hit a second problem I'm now working to fix.

**Comment by rhc54** [comment]
Correction - the original job does indeed "hang" as no timeout was given for the "get" operation. We probably need to add something in the job termination logic to cleanup any lingering "get" calls for information on a job that has terminated.
