### ISSUE TITLE
Why do we need C++ to build PMIx?

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix#1177]
Apparently, our configure logic requires installation of g++ in order to find the pthreads library, even when that library and its header are already installed as part of gcc. There is no other dependency on C++ in this code base, so I'm concluding that this must be an error.

**Comment by rhc54** [comment]
Also, we don't apparently look for ```flex``` during configure, but we require it as soon as you try to compile. This is also an error - configure is supposed to check for all required components.

**Comment by jjhursey** [comment]
Good catch. I noticed these dependencies when setting up the Docker environment for the cross-version tester and it seems curious to me that PMIx had that dependency.
