### ISSUE TITLE
MCA modules should depend on libpmix.so if using symbols from there

### ISSUE THREAD

**Issue by krempel-pt** [pmix/pmix#1186]
### What version of the PMIx Reference Library are you using?
v3.1.2

### Describe how PMIx was installed
Compiled from the release tarball using
configure --disable-static --enable-shared --enable-pmi-backward-compatibility --with-munge

### Please describe the system on which you are running
Operating system/version: Fedora 29
Computer hardware: Intel Core i7-8550U
Network type: none

-----------------------------

## Details of the problem

Some (or all) of the mca modules shared object files are lacking an DT_NEEDED entry to libpmix.so, even if they are using symbols from there.

In my case, the PMIx server using the PMIx server library is implemented as a plugin to the RTE, loaded if needed using dlopen(). Without the RTLD_GLOBAL flag, this leads to the error:
```
pmix_mca_base_component_repository_open: unable to open mca_bfrops_v12: /home/krempel/Projekte/PMIx/pmix-3.1.2/install/lib/pmix/mca_bfrops_v12.so: undefined symbol: pmix_buffer_t_class (ignored)
pmix_mca_base_component_repository_open: unable to open mca_bfrops_v20: /home/krempel/Projekte/PMIx/pmix-3.1.2/install/lib/pmix/mca_bfrops_v20.so: undefined symbol: pmix_bfrops_base_print_datatype (ignored)
pmix_mca_base_component_repository_open: unable to open mca_bfrops_v21: /home/krempel/Projekte/PMIx/pmix-3.1.2/install/lib/pmix/mca_bfrops_v21.so: undefined symbol: pmix_bfrops_base_print_ptr (ignored)
pmix_mca_base_component_repository_open: unable to open mca_bfrops_v3: /home/krempel/Projekte/PMIx/pmix-3.1.2/install/lib/pmix/mca_bfrops_v3.so: undefined symbol: pmix_bfrops_base_print_ptr (ignored)
[...]
pspmix_server_init: PMIx_server_init() failed: SILENT_ERROR
```
If I manually add DT_NEEDED to libpmix.so into mca_bfrops_v12.so it is working.

Usually the plugins to our RTE should not be loaded with RTLD_GLOBAL, so currently a hackish exception has to be made for pmix. I think this is a bug since the plugins are using symbols without depending on their source.

Unfortunately I am not fairly familiar with the pmix build system to provide a suitable patch, easily.

**Comment by rhc54** [comment]
Hmmm...timely report! I have been working towards a 3.1.3 release for later this week, but will ensure this gets fixed before doing so. I'm somewhat out today but should hopefully be able to address this tomorrow. Thanks!

**Comment by ggouaillardet** [comment]
@krempel-pt FWIW, Open MPI chose __not__ to have MCA modules depend on `libmpi.so` (and other internal libs). IIRC, the rationale is so ISV can ship binary components that can work on a version of Open MPI that is slightly different from the one used to build the component.

As a consequence, `RTLD_GLOBAL` is needed if `libmpi.so` is to be `dlopen()`'ed (and this is what Java bindings and `mpi4py` do)

Obviously, PMIx is free not to do things differently, or make it yet an other `configure` option.

Meanwhile, you can `configure --disable-dlopen ...` and `dlopen(libpmix.so, ...`) should work just fine without `RTLD_GLOBAL`.

**Comment by rhc54** [comment]
@ggouaillardet The issue here is when doing a static build - OMPI also ran into this problem and added the primary library for each project to that project's MCA components.

**Comment by ggouaillardet** [comment]
The issue description clearly states `configure --disable-static --enable-shared ...` and `dlopen()` so I do not think static builds fit into this picture.

But you are right Open MPI made such changes since `v3.0.x` and I completely missed it !

**Comment by rhc54** [comment]
@ggouaillardet Ouch - yeah, I shouldn't try to read issues while still recovering from anesthesia ☹️ 

> IIRC, the rationale is so ISV can ship binary components that can work on a version of Open MPI that is slightly different from the one used to build the component.

I raised this on the OMPI call this morning and your analysis about consequences is true. However, because we weren't guaranteeing internal ABI across releases (even minor ones), it turns out that this situation has always been true. Thus, adding the links didn't make anything worse and solved an mpi4py issue identical to the one described here. So we'll follow that lead as it fixes this problem and would likely have been required for the mpi4py scenario in OMPI anyway.
