### ISSUE TITLE
Event race condition between registration and cached delivery

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix#1189]
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

v3.1 branch [HEAD](https://github.com/pmix/pmix/commit/b3e93da2a5419b585f25716b56cc6273f56d25c4) with Open MPI v4.0.x (approximate HEAD of branch)

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git clone of v3.1 branch

### Please describe the system on which you are running

* Operating system/version: RHEL 7.5
* Computer hardware: ppc64le
* Network type: TCP

-----------------------------

## Details of the problem

I'm working a bug with Open MPI's debugger support through `mpirun -tv ...` which uses PMIx events instead of the MPIR_debug_gate [here](https://github.com/open-mpi/ompi/blob/v4.0.x/ompi/mca/rte/orte/rte_orte_module.c#L164-L199) to release the application process from MPI_Init. I can reproduce with 2 processes on a single node (`mpirun -tv -np 2 ./hello`)

I've noticed that there is a race condition between when the PMIx client receives the local `pmix_hdlr_reg_cbfunc_t` call and when it starts receiving events on the `pmix_notification_fnt_t` handler.

Open MPI assumes that the registration callback is called before any notification callback. If that is not true then an event is lost as it falls out of [this loop](https://github.com/pmix/pmix/blob/v3.1/src/event/pmix_event_registration.c#L850-L851) since the index does not match. The index is resolved in the registration callback [here](https://github.com/open-mpi/ompi/blob/v4.0.x/opal/mca/pmix/pmix3x/pmix3x.c#L1259).

In the debugger case the `MPI-DEBUGGER-ATTACH` event is already cached in the server, so it is immediately sent to the client once the server sees the registration message from the client. This triggers a race in the client side [reg_event_hdlr](https://github.com/pmix/pmix/blob/v3.1/src/event/pmix_event_registration.c#L455) function since it calls [_add_hdlr](https://github.com/pmix/pmix/blob/v3.1/src/event/pmix_event_registration.c#L714) (which initiates the registration with the server) but since [`PMIX_ERR_WOULD_BLOCK`](https://github.com/pmix/pmix/blob/v3.1/src/event/pmix_event_registration.c#L326) is returned then the [registration callback](https://github.com/pmix/pmix/blob/v3.1/src/event/pmix_event_registration.c#L834), which triggers the registration ack to Open MPI, is not triggered in this context.

The progress thread is not allowed to progress the next event which could be the registration or the event from the server.

**Comment by jjhursey** [comment]
From reading the v3 standard document, there doesn't seem to be language associated with the ordering semantics of the `pmix_hdlr_reg_cbfunc_t` and `pmix_notification_fnt_t` callback functions to `PMIx_Register_event_handler`. So we need to clarify that.

My leaning would be that the PMIx library should guarantee that the registration callback is triggered and returned before it starts delivering events. This allows the caller to set up data structures to handle events in the registration callback and not have to cache events at the client level.

**Comment by rhc54** [comment]
> From reading the v3 standard document, there doesn't seem to be language associated with the ordering semantics of the `pmix_hdlr_reg_cbfunc_t` and `pmix_notification_fnt_t` callback functions to `PMIx_Register_event_handler`. So we need to clarify that.

Agreed - for consistency across the document, we should require that registration return prior to any notifications



> My leaning would be that the PMIx library should guarantee that the registration callback is triggered and returned before it starts delivering events. This allows the caller to set up data structures to handle events in the registration callback and not have to cache events at the client level.

Agreed - I can make that modification this afternoon.

**Comment by jjhursey** [comment]
PR #1190 (master) and PR #1194 (v3.1) fix this issue.

**Comment by jjhursey** [comment]
Fixed now that the above PRs have been merged

**Comment by jjhursey** [comment]
Ref two Open MPI tickets impacted:
 * https://github.com/open-mpi/ompi/issues/6613#issuecomment-486713779 (OMPI v4.0.x)
 * https://github.com/open-mpi/ompi/issues/5501#issuecomment-488639797 (OMPI v3.0.x)
