### ISSUE TITLE
pfexec error message

### ISSUE THREAD

**Issue by tonycurtis** [pmix/pmix#1228]
Thank you for taking the time to submit an issue!

## Background information

Started getting error from PMIx clients

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

github master @ 2f0a53d43a5ee5d4a7446636308f58be0eac0f3d

PRRTE @ a967a24666e4d195d27062958b8fcf0be47efe95

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git-clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: IB

-----------------------------

## Details of the problem

PMIx client (via prun) giving this error:

```shell
[login2:195137] pmix_mca_base_component_repository_open: "mca_pfexec_linux" does not appear to be a valid pfexec MCA dynamic component (ignored): /gpfs/projects/ChapmanGroup/opt/pmix/git/lib/pmix/mca_pfexec_linux.so: undefined symbol: mca_pfexec_linux_component. ret -1
[login2:195137] [../../../../prrte-git/orte/tools/prun/prun.c:809] PMIx Error: NOT-FOUND
```

**Comment by rhc54** [comment]
Sigh - gotta love "visibility"! Sorry about that - and welcome back!

**Comment by tonycurtis** [comment]
+1
