### ISSUE TITLE
Type mismatch in PTL header field portability transformation

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix#1238]
The datatype for `nbytes` field in the header is `size_t`:
https://github.com/pmix/pmix/blob/master/src/mca/ptl/ptl_types.h#L113

However `htonl` function is used that only address uint32_t
https://github.com/pmix/pmix/blob/master/src/mca/ptl/ptl_types.h#L279

**Comment by jjhursey** [comment]
So the concern is of the wasted 4 bytes in the `size_t` that won't be used by the `unit32_t`. Not a bug, just minor inefficiency. Will have to look at compatibility across versions.
