### ISSUE TITLE
Cross-version support is broken on master

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix#1259]
Now that we are actually testing cross-version branches, it appears that master has developed a problem:
```
============================== Summary (Client) ==============================
Run PASS: master -> master
Run ***FAILED***: master -> v3.1
Run ***FAILED***: master -> v3.0
Run ***FAILED***: master -> v2.2
Run ***FAILED***: master -> v2.1
Run ***FAILED***: master -> v2.0
Run ***FAILED***: master -> v1.2
Run ***FAILED***: master -> fix
Run ***FAILED***: v3.1 -> master
Run PASS: v3.1 -> v3.1
Run PASS: v3.1 -> v3.0
Run PASS: v3.1 -> v2.2
Run PASS: v3.1 -> v2.1
Run PASS: v3.1 -> v2.0
Run PASS: v3.1 -> v1.2
Run PASS: v3.1 -> fix
Run ***FAILED***: v3.0 -> master
Run PASS: v3.0 -> v3.1
Run PASS: v3.0 -> v3.0
Run PASS: v3.0 -> v2.2
Run PASS: v3.0 -> v2.1
Run PASS: v3.0 -> v2.0
Run PASS: v3.0 -> v1.2
Run PASS: v3.0 -> fix
Run ***FAILED***: v2.2 -> master
Run PASS: v2.2 -> v3.1
Run PASS: v2.2 -> v3.0
Run PASS: v2.2 -> v2.2
Run PASS: v2.2 -> v2.1
Run PASS: v2.2 -> v2.0
Run PASS: v2.2 -> v1.2
Run PASS: v2.2 -> fix
Run ***FAILED***: v2.1 -> master
Run PASS: v2.1 -> v3.1
Run PASS: v2.1 -> v3.0
Run PASS: v2.1 -> v2.2
Run PASS: v2.1 -> v2.1
Run PASS: v2.1 -> v2.0
Run PASS: v2.1 -> v1.2
Run PASS: v2.1 -> fix
Run PASS: v2.0 -> v2.0
Run ***FAILED***: v2.0 -> fix
Run PASS: v1.2 -> v1.2
Run PASS: v1.2 -> fix
Run ***FAILED***: fix -> master
Run PASS: fix -> v3.1
Run PASS: fix -> v3.0
Run PASS: fix -> v2.2
Run PASS: fix -> v2.1
Run PASS: fix -> v2.0
Run PASS: fix -> v1.2
Run PASS: fix -> fix
============================== Summary (Tool) ==============================
Run PASS: master -> master (Tool)
Run ***FAILED***: master -> v3.1 (Tool)
Run ***FAILED***: master -> v3.0 (Tool)
Run ***FAILED***: master -> v2.2 (Tool)
Run ***FAILED***: master -> v2.1 (Tool)
Run ***FAILED***: master -> v2.0 (Tool)
Run PASS: master -> v1.2 (Tool)
Run ***FAILED***: master -> fix (Tool)
Run ***FAILED***: v3.1 -> master (Tool)
Run PASS: v3.1 -> v3.1 (Tool)
Run PASS: v3.1 -> v3.0 (Tool)
Run PASS: v3.1 -> v2.2 (Tool)
Run PASS: v3.1 -> v2.1 (Tool)
Run PASS: v3.1 -> v2.0 (Tool)
Run PASS: v3.1 -> v1.2 (Tool)
Run PASS: v3.1 -> fix (Tool)
Run ***FAILED***: v3.0 -> master (Tool)
Run PASS: v3.0 -> v3.1 (Tool)
Run PASS: v3.0 -> v3.0 (Tool)
Run ***FAILED***: v3.0 -> v2.2 (Tool)
Run PASS: v3.0 -> v2.1 (Tool)
Run PASS: v3.0 -> v2.0 (Tool)
Run PASS: v3.0 -> v1.2 (Tool)
Run ***FAILED***: v3.0 -> fix (Tool)
Run ***FAILED***: v2.2 -> master (Tool)
Run ***FAILED***: v2.2 -> v3.1 (Tool)
Run PASS: v2.2 -> v3.0 (Tool)
Run ***FAILED***: v2.2 -> v2.2 (Tool)
Run PASS: v2.2 -> v2.1 (Tool)
Run PASS: v2.2 -> v2.0 (Tool)
Run PASS: v2.2 -> v1.2 (Tool)
Run ***FAILED***: v2.2 -> fix (Tool)
Run ***FAILED***: v2.1 -> master (Tool)
Run PASS: v2.1 -> v3.1 (Tool)
Run PASS: v2.1 -> v3.0 (Tool)
Run PASS: v2.1 -> v2.2 (Tool)
Run PASS: v2.1 -> v2.1 (Tool)
Run PASS: v2.1 -> v2.0 (Tool)
Run PASS: v2.1 -> v1.2 (Tool)
Run ***FAILED***: v2.1 -> fix (Tool)
Run PASS: v2.0 -> v2.0 (Tool)
Run ***FAILED***: v2.0 -> fix (Tool)
Run PASS: v1.2 -> v1.2 (Tool)
Run PASS: v1.2 -> fix (Tool)
Run ***FAILED***: fix -> master (Tool)
Run PASS: fix -> v3.1 (Tool)
Run PASS: fix -> v3.0 (Tool)
Run PASS: fix -> v2.2 (Tool)
Run PASS: fix -> v2.1 (Tool)
Run PASS: fix -> v2.0 (Tool)
Run PASS: fix -> v1.2 (Tool)
Run PASS: fix -> fix (Tool)
```
The `fix` branch in this case was a revert of https://github.com/pmix/pmix/commit/997b42b4134ce5db7c397073f24b64968a6e6ff6 as per the teleconf. Unfortunately, this does not impact the problem.

I suggest someone do a `git bisect` to see if we can isolate where it failed.

**Comment by artpol84** [comment]
Updated state:
<details>
<summary>Summary (Client): ALL PASSED </summary>

Run PASS: master -> master
Run PASS: master -> v3.1
Run PASS: master -> v3.0
Run PASS: master -> v2.2
Run PASS: master -> v2.1
Run PASS: master -> v2.0
Run PASS: master -> v1.2
Run PASS: v3.1 -> master
Run PASS: v3.1 -> v3.1
Run PASS: v3.1 -> v3.0
Run PASS: v3.1 -> v2.2
Run PASS: v3.1 -> v2.1
Run PASS: v3.1 -> v2.0
Run PASS: v3.1 -> v1.2
Run PASS: v3.0 -> master
Run PASS: v3.0 -> v3.1
Run PASS: v3.0 -> v3.0
Run PASS: v3.0 -> v2.2
Run PASS: v3.0 -> v2.1
Run PASS: v3.0 -> v2.0
Run PASS: v3.0 -> v1.2
Run PASS: v2.2 -> master
Run PASS: v2.2 -> v3.1
Run PASS: v2.2 -> v3.0
Run PASS: v2.2 -> v2.2
Run PASS: v2.2 -> v2.1
Run PASS: v2.2 -> v2.0
Run PASS: v2.2 -> v1.2
Run PASS: v2.1 -> master
Run PASS: v2.1 -> v3.1
Run PASS: v2.1 -> v3.0
Run PASS: v2.1 -> v2.2
Run PASS: v2.1 -> v2.1
Run PASS: v2.1 -> v2.0
Run PASS: v2.1 -> v1.2
Run PASS: v2.0 -> v2.0
Run PASS: v1.2 -> v1.2
</details>

**Summary (Tool):**

Run PASS: master -> master (Tool)
Run PASS: master -> v3.1 (Tool)
Run PASS: master -> v3.0 (Tool)
Run PASS: master -> v2.2 (Tool)
Run PASS: master -> v2.1 (Tool)
Run PASS: master -> v2.0 (Tool)
Run PASS: master -> v1.2 (Tool)
Run PASS: v3.1 -> master (Tool)
Run PASS: v3.1 -> v3.1 (Tool)
Run PASS: v3.1 -> v3.0 (Tool)
Run PASS: v3.1 -> v2.2 (Tool)
Run PASS: v3.1 -> v2.1 (Tool)
Run PASS: v3.1 -> v2.0 (Tool)
Run PASS: v3.1 -> v1.2 (Tool)
Run ***FAILED***: v3.0 -> master (Tool)
Run PASS: v3.0 -> v3.1 (Tool)
Run PASS: v3.0 -> v3.0 (Tool)
Run ***FAILED***: v3.0 -> v2.2 (Tool)
Run PASS: v3.0 -> v2.1 (Tool)
Run PASS: v3.0 -> v2.0 (Tool)
Run PASS: v3.0 -> v1.2 (Tool)
Run ***FAILED***: v2.2 -> master (Tool)
Run ***FAILED***: v2.2 -> v3.1 (Tool)
Run PASS: v2.2 -> v3.0 (Tool)
Run ***FAILED***: v2.2 -> v2.2 (Tool)
Run PASS: v2.2 -> v2.1 (Tool)
Run PASS: v2.2 -> v2.0 (Tool)
Run PASS: v2.2 -> v1.2 (Tool)
Run ***FAILED***: v2.1 -> master (Tool)
Run PASS: v2.1 -> v3.1 (Tool)
Run PASS: v2.1 -> v3.0 (Tool)
Run PASS: v2.1 -> v2.2 (Tool)
Run PASS: v2.1 -> v2.1 (Tool)
Run PASS: v2.1 -> v2.0 (Tool)
Run PASS: v2.1 -> v1.2 (Tool)
Run PASS: v2.0 -> v2.0 (Tool)
Run PASS: v1.2 -> v1.2 (Tool)

**Comment by artpol84** [comment]
I see a set of different problems:
* The main one why master/v2.2/v3.1 clients are failing with v3.0/v2.1 servers is that v3.0 and v2.1 do not support connections from TOOL+CLIENT [[link](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp.c#L1048:L1053)].
These new entities were introduced in c9842fe9 prior to (tag: v3.1.0rc2).
I assume that the connection from the tool with an extended set of entities to the tool with legacy support (according to the classification by the [[link](https://github.com/pmix/pmix/blob/master/src/mca/ptl/tcp/ptl_tcp.c#L1003:L1014)]) is not expected to work.
* The second issue is allowing v3.1 to pass the cross-version test by using usock. Fixed in #1271.
* The reason why v2.2 is not passing cross-version test wile not having #1272 fix is that v22 protocol is not known [[link](https://github.com/pmix/pmix/blob/master/src/mca/ptl/usock/ptl_usock_component.c#L593:L601)]

**Comment by artpol84** [comment]
@rhc54 because c9842fe was introduced starting from tag: v3.1.0rc2 I this type of cross-version interoperation is not supported  by v3.0-srv/v3.1-cli combination starting from v3.1.0.
**So what we observe is not a regression and should not hold v3.1.3.**

**Comment by rhc54** [comment]
> The second issue is allowing v3.1 to pass the cross-version test by using usock. Fixed in #1271.

I don't understand this statement - perhaps what you meant is that v3.1 was _failing_ because it was trying to use the usock component, and now passes because we exclude usock?

> The reason why v2.2 is not passing cross-version test is that v22 protocol is not known

I think the real cause here is that the v2.2 tool is again (because it is a tool+client) incorrectly attempting to use the usock component. It passes if it uses the tcp component as it should, yes?

> I assume that the connection from the tool with an extended set of entities to the tool with legacy support (according to the classification by the [link]) is not expected to work.

It was expected to work, but sadly the breakage wasn't detected. We will have to figure out the best way to address it, most likely with some combination of patches, NEWS items, and email to the list

> So what we observe is not a regression and should not hold v3.1.3.

I think there is a misunderstanding here. It isn't a question of a regression or not - it is a question of newly detected problems that need to be addressed. We have improved/fixed our testing and need to fully assess where we really are with respect to cross-version support, and then figure out how to address any shortcomings.

**Comment by artpol84** [comment]
> I don't understand this statement - perhaps what you meant is that v3.1 was failing because it was trying to use the usock component, and now passes because we exclude usock?

See the results: v3.0/v3.1 is passing though we know it should not.

Run FAILED: v3.0 -> master (Tool)
Run PASS: v3.0 -> v3.1 (Tool)
Run PASS: v3.0 -> v3.0 (Tool)
Run FAILED: v3.0 -> v2.2 (Tool)

**Comment by artpol84** [comment]
> I think there is a misunderstanding here. It isn't a question of a regression or not - it is a question of newly detected problems that need to be addressed. We have improved/fixed our testing and need to fully assess where we really are with respect to cross-version support, and then figure out how to address any shortcomings.

Surely we need to address those. But as you know we have people waiting for the fixes in 3.1.3 for quite a while now.
So what is important to me is to provide those fixes and fix these newly uncovered ones as part of 3.1.4.

Previous concern was that v3.1.3 will introduce regression and is breaking backwards compatibility so we wanted to investigate the issue before releasing.
Now we know it’s not a regression so I’m advocating for v3.1.3 release to happen with fixes we already have.

**Comment by rhc54** [comment]
@artpol84 Perhaps the root problem here is a misunderstanding of how an open source project relates to a corporation. When a corporate customer has a problem with a particular release, the expectation is that the company will take the head of the community's branch for that release and check to see if the problem has already been fixed and is simply awaiting release. If not, then the company can find the problem and fix it. The company will then provide the customer with a patched version (either thru an actual patch, or a tarball/rpm made from the company's repository, or whatever), push the patch upstream to the community's repo, and tell the customer what official release version should eventually contain the fixes. This way the customer can move forward without waiting on the project.

Open source projects are almost always composed of volunteers and/or participants from different organizations (each with their own priorities), which means there is simply no way such a project can "commit" to a release date. There are too many conflicting priorities between the participants and the various consumers of the releases. If you look at an example like OMPI, you'll see that releases can sometimes be delayed by as much as 6-12 months while the community works to fix bugs of importance to various groups and deal with issues that arise during the release process. It's a pretty typical scenario seen across many projects, which is why companies maintain their own "clones" to handle bugs.

I understand your pressure, but the correct solution is for you to follow typical practices. We cannot release something that is broken just because it happens to include fixes relevant to your specific customer. We owe it to everyone else using the software to complete the assessment (see https://github.com/pmix/pmix-tests/pull/9 for a current status of the testing software and what may be broken) and address the problems, both for v3.1 and looking backward.

As I said, the plan may consist of a combination of patches, NEWS, and announcements - but we do need to know the actual situation and have a plan.

**Comment by artpol84** [comment]
I’m looking at this from the different angle.
* the fixes already in v3.1 + the connection fix pending are affecting v3.1 only users and are there to immediately help those who rely on it. I don’t think it’s only our customers.
* the cross-version issue affects all branches and require a complex set of measures as you pointed out. It affects users multi-version configurations.

My proposal suits both user groups as we 
1. release hot fixes to v3.1-only users now as part of v3.1.3 and 
2. provide a broader group with the warning about cross-version inconsistency and work on a complex solution that will require inter-version coordination.

> > I assume that the connection from the tool with an extended set of entities to the tool with legacy support (according to the classification by the [link]) is not expected to work.
> It was expected to work, but sadly the breakage wasn't detected.

Can you elaborate how exactly? Should v3.1 downgrade to a legacy tool?

**Comment by artpol84** [comment]
> As I said, the plan may consist of a combination of patches, NEWS, and announcements - but we do need to know the actual situation and have a plan.

Out of curiosity, why do you think patches will be required? If one is about to patch and rebuild from sources isn’t it easier to simply update to a new bug fix release?

**Comment by rhc54** [comment]
As part of the release process, we will take time to scan the commit history and identify any commits that should be brought across. I think there have been one or two that floated by and weren't PR'd. I plan to do that once I finish "day 1" of the tutorial I'm working on.

We will then release v3.1.3 when it is complete (which includes spending time in OMPI for MTT testing to thoroughly stress it), we have assessed the extent of the cross-version problem, and can communicate both the situation as well as a plan for addressing. We owe the user community at least that much. Depending on what is found, we may delay v3.1.3 until it fully passes the cross-version tests - that decision will be made once we complete the assessment.

Critical path for the assessment right now is to complete the "make check" extensions to the xversion.py tester as per https://github.com/pmix/pmix-tests/pull/9

> Should v3.1 downgrade to a legacy tool?

I'm not sure what is meant by "downgrading" v3.1 to a "legacy tool", but I see no way to adequately determine what to do about such questions until after the assessment is completed.

> Out of curiosity, why do you think patches will be required? If one is about to patch and rebuild from sources isn’t it easier to simply update to a new bug fix release?

The _plan_ may consist of patches being applied to various release branches - obviously, we wouldn't distribute bare patches 😄

**Comment by jjhursey** [comment]
What we could do is a 3.1.3rc3 with the fixes we have so far for those that need to pick it up early and include a note that we are investigating a cross-version issue with tool support that will likely cause a new rc before the final release (we can work on the wording). This signals to folks that this is not likely the 'final' rc for the series, and to watch a particular Issue number to watch for more details.

Until a proper assessment is done I'm hesitant to release 3.1.3. If the assessment turns up a few small things that we can fix quickly then we can roll them in 3.1.3 and release. If it requires bigger changes then we can have a discussion about releasing 3.1.3 with a full description of which combinations work and under which circumstances - then follow with a 3.1.4.

**Comment by rhc54** [comment]
Current status report from the updated xversion.py test:
```shell
============================== Summary (Make Check Failures) ==============================
Run ***FAILED***: master -> v3.1  [-n 2 --test-spawn -e ]
Run ***FAILED***: master -> v3.0  [-n 2 --test-spawn -e ]
Run ***FAILED***: master -> v2.2  [-n 2 --test-spawn -e ]
Run ***FAILED***: master -> v2.1  [-n 2 --test-spawn -e ]
Run ***FAILED***: master -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: master -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: master -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: master -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: master -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v3.1 -> master  [-n 2 --test-spawn -e ]
Run ***FAILED***: v3.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.1 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v3.0 -> master  [-n 2 --test-spawn -e ]
Run ***FAILED***: v3.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.2 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.2 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.1 -> master  [-n 2 --test-spawn -e ]
Run ***FAILED***: v2.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
```
I'll take a look at the spawn failures. For the rest of these, can someone more familiar with those tests perhaps give us an assessment as to which ones should be passing for these combinations? For example, I'm pretty sure that "resolve peers" never worked in the v1.x series.

**Comment by rhc54** [comment]
Update: I have fixed the spawn test failures:
```shell
============================== Summary (Make Check Failures) ==============================
Run ***FAILED***: master -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: master -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: master -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v3.1 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v3.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.2 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v2.0  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 5 --test-resolve-peers --ns-dist "1:2:2" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
```

**Comment by rhc54** [comment]
Continued working on these. Found that `test-resolve-peers` doesn't work on the v1.2 and v2.0 series for good reasons that are not worth fixing, so disabled that test on combinations involving those series. This leaves us with:
```shell
============================== Summary (Make Check Failures) ==============================
Run ***FAILED***: master -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: master -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v3.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v3.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.2 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 5 --test-replace 100:0,1,10,50,99 -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
```

**Comment by rhc54** [comment]
Digging some more, it is pretty clear that `test-replace` doesn't work on v1.2, so let's turn it off...and so we are down to the fence tests:
```shell
============================== Summary (Make Check Failures) ==============================
Run ***FAILED***: master -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.1 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v3.0 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.1 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v2.0 -> v2.0  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:0]" -e ]
Run ***FAILED***: v1.2 -> v1.2  [-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]" -e ]
```
@artpol84 @karasevb Do you know if these tests should be working on these combinations?

**Comment by karasevb** [comment]
The `--fence` errors are caused by an opposite ranking scheme in the test suite: versions v1.2 and v2.0 assume that the ranking goes throughout namespaces. The different ranking is used for the next versions (since from v2.1), where the rank numbers start from 0 for each namespace. 

The expression `-n 4 --ns-dist 3:1 --fence "[db | 0:;1:0]"` is not working for v1.2/v2.0 because here first three ranks are assigned to nspace-0 and rank 3 in nspace-1, but this expression forces to get rank-0 from nspace-1 that leads to failure. The working expression is `-n 4 --ns-dist 3:1 --fence "[db | 0:;1:3]"`.
This ranking scheme is not correct and should be fixed for v1.2/v2.0 by cherry-picking from 83b3d0d

**Comment by artpol84** [comment]
Thanks, @karasevb!
@rhc54 please see if this answers your question.

**Comment by rhc54** [comment]
Yep - thanks!! This has now been resolved.
