### ISSUE TITLE
failure with CFLAGS=-m32

### ISSUE THREAD

**Issue by ggouaillardet** [pmix/pmix#1332]
When `master` (I did not try other branches) is configure'd with `CFLAGS=-m32`

For a yet unknown reason, `CFLAGS` does not contain `-m32` when `AC_CHECK_TYPES(__int128)` is invoked, so `__int128` is detected.

For example, the following program

```c
__int128 foo;
```

```gcc -c foo.c``` works fine, but ```gcc -c -m32 foo.c``` fails (and this is what we would expect here).

**Comment by ggouaillardet** [comment]
@rhc54 The error is triggered by pmix/pmix@c65bcd7370eef57756a16f8894b27d800529d954

In the case of `-m32`, we do want to test with the user-provided `CFLAGS`.

**Comment by rhc54** [comment]
Okay, I see - let me try to find a workaround. We ran into a problem with external CFLAGS on another configure test which motivated the change. I guess we have to come up with some scheme for which ones to allow and which to avoid.

**Comment by ggouaillardet** [comment]
yep, my first guess would be to either whilelist `-m32` or blacklist `-Werror`

**Comment by rhc54** [comment]
Yeah, either way should suffice. Maybe we should just blacklist `-Werror` for now as that was the real source of the trouble? Spewing warnings from `-Wextra` shouldn't interfere with the configure tests.

**Comment by ggouaillardet** [comment]
sounds good to me!

**Comment by rhc54** [comment]
Refs #1331 , #1333

**Comment by rhc54** [comment]
All target branches updated!
