### ISSUE TITLE
Fastpath "get" is truncating keys

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix#1375]
I've been seeing something that had me puzzled - whenever we did a modex to obtain data and passed the results down to a process, we wound up turning around and asking the server for the data anyway. In digging a little deeper, I finally discovered that the `fastpath` method for obtaining values is returning truncated keys.

You can see this easily by running `./simptest` in the `test/simple` directory:
```
$ ./simptest
Testing version 4.0.0a1
Collecting inventory
Inventory collected: 0
[Ralphs-iMac-2.local:39098] Client ns foobar rank 0: Running
[Ralphs-iMac-2.local:39098] CLIENT SERVER URI: pmix-server.39084;tcp4://127.0.0.1:55902
simpclient EVENT HANDLER REGISTRATION RETURN STATUS 0, ref=0
foobar:0 Model event handler called with status -147(PMIX MODEL DECLARED)
foobar:0	pmix.pgm.model:	TEST
foobar:0	pmix.mdl.name:	PMIX
foobar:0	pmix.evname:	SIMPCLIENT-MODEL
[Ralphs-iMac-2.local:39098] Client: ERRHANDLER REGISTRATION CALLBACK CALLED WITH STATUS 0, ref=1
[Ralphs-iMac-2.local:39098] Client foobar:0 universe size 1
[Ralphs-iMac-2.local:39098] Client ns foobar rank 0 cnt 0: PMIx_Get foobar-0-local-0 returned correct
[Ralphs-iMac-2.local:39098] Client ns foobar rank 0 testing internal modex blob
[Ralphs-iMac-2.local:39098] 	Key: fo
[Ralphs-iMac-2.local:39098] 	Key: pm
[Ralphs-iMac-2.local:39098] 	Key: pm
[Ralphs-iMac-2.local:39098] 	Key: pm
[Ralphs-iMac-2.local:39098] 	Key: pm
[Ralphs-iMac-2.local:39098] 	Key: pm
[Ralphs-iMac-2.local:39098] Client ns foobar rank 0: Finalizing
Client ns foobar rank 0:PMIx_Finalize successfully completed
SIMPTEST: Model event handler called with status -147(PMIX MODEL DECLARED)
	pmix.pgm.model:	PMIX
	pmix.mdl.name:	test
	pmix.evname:	SIMPTEST-MODEL
Test finished OK!
```
Note that the keys in the modex are all truncated at two characters. Adding `PMIX_MCA_gds=hash` to the environment:
```
$ ./simptest
Testing version 4.0.0a1
Collecting inventory
Inventory collected: 0
[Ralphs-iMac-2.local:39152] Client ns foobar rank 0: Running
[Ralphs-iMac-2.local:39152] CLIENT SERVER URI: pmix-server.39138;tcp4://127.0.0.1:55906
simpclient EVENT HANDLER REGISTRATION RETURN STATUS 0, ref=0
foobar:0 Model event handler called with status -147(PMIX MODEL DECLARED)
foobar:0	pmix.pgm.model:	TEST
foobar:0	pmix.mdl.name:	PMIX
foobar:0	pmix.evname:	SIMPCLIENT-MODEL
[Ralphs-iMac-2.local:39152] Client: ERRHANDLER REGISTRATION CALLBACK CALLED WITH STATUS 0, ref=1
[Ralphs-iMac-2.local:39152] Client foobar:0 universe size 1
[Ralphs-iMac-2.local:39152] Client ns foobar rank 0 cnt 0: PMIx_Get foobar-0-local-0 returned correct
[Ralphs-iMac-2.local:39152] Client ns foobar rank 0 testing internal modex blob
[Ralphs-iMac-2.local:39152] 	Key: pmix.srvr.uri
[Ralphs-iMac-2.local:39152] 	Key: pmix.grank
[Ralphs-iMac-2.local:39152] 	Key: pmix.lrank
[Ralphs-iMac-2.local:39152] 	Key: pmix.nrank
[Ralphs-iMac-2.local:39152] 	Key: pmix.nodeid
[Ralphs-iMac-2.local:39152] 	Key: pmix.hname
[Ralphs-iMac-2.local:39152] 	Key: foobar-0-internal
[Ralphs-iMac-2.local:39152] 	Key: foobar-0-local-0
[Ralphs-iMac-2.local:39152] 	Key: foobar-0-remote-0
[Ralphs-iMac-2.local:39152] Client ns foobar rank 0: Finalizing
Client ns foobar rank 0:PMIx_Finalize successfully completed
SIMPTEST: Model event handler called with status -147(PMIX MODEL DECLARED)
	pmix.pgm.model:	PMIX
	pmix.mdl.name:	test
	pmix.evname:	SIMPTEST-MODEL
Test finished OK!
```
yields the expected results - complete keys in the returned info array. I have checked this on v2.2, v3.1, and master. All show the identical problem, and all were upgraded with the `fastpath` code.

The modex involves a call to `PMIx_Get` with a NULL key, thereby requesting the return of an info array containing all values for that process If I bypass the `fastpath` method when we make a NULL key request, then the problem is resolved.

However, it begs the question: why are the keys being truncated? Does it only happen when returning an info array, or is there something fundamentally wrong in the `fastpath` code?

**Comment by jjhursey** [comment]
A few notes from the teleconf:
 * Adding a `key != NULL &&` check to [this](https://github.com/pmix/pmix/blob/master/src/client/pmix_client_get.c#L104) statement fixed the problem because it will threadshift and then choose to use `hash` later. The later point has a similar check for the `key == NULL` to choose `hash` over the dstore component.
 * The above fix will make this code path function correctly. So we will pursue that change for v3.x and v2.x branches.
 * @artpol84 From my understanding, dstore still has an issue here with non-NULL keys that will return an array of values where it truncates the keys in that array. We can probably work up a test case for it (maybe using the network coordinates since they return an array). So there is still something to be fixed in dstore.

**Comment by artpol84** [comment]
We will take a look, thank you.
The repro would be appreciated.
@karasevb, FYI

**Comment by artpol84** [comment]
@jjhursey,

> @artpol84 From my understanding, dstore still has an issue here with non-NULL keys that will return an array of values where it truncates the keys in that array. We can probably work up a test case for it (maybe using the network coordinates since they return an array). So there is still something to be fixed in dstore.

Is this an observed behavior? #1382 fixes the key truncation.
Our current understanding is that the fixed bug key name truncation was related only to a codepath that corresponds to the key == NULL case.
This means we don’t envision similar issues with the array case. Though we haven’t yet checked. 

So I’m trying to see if this was a concern or an observed bug.

**Comment by jjhursey** [comment]
Ralph observed the bug with simptest. I don't know of other occurrences.
