### ISSUE TITLE
PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113

### ISSUE THREAD

**Issue by ktpedre** [pmix/pmix#1381]
### Background information
Running PMIX 2.2.3 RC1 with OpenMPI 3.1.4 and SLURM 17.11.12.  Here are the configure lines for each:

./configure --prefix=/opt/atse/pmix --disable-pmi-backward-compatibility --enable-static

./configure --prefix=/opt/atse/mpi/openmpi3-gnu7/3.1.4 --disable-static --enable-shared --enable-builtin-atomics --with-sge --enable-mpi-cxx --with-pmi=/usr --with-pmix=/opt/atse/pmix --with-libevent=external --with-hwloc=external --with-verbs --with-hcoll=/opt/mellanox/hcoll --with-knem=/opt/knem-1.1.3.90mlnx1 --with-ucx=/opt/atse/libs/gnu7/openucx/1.5.2

./configure --build=aarch64-redhat-linux-gnu --host=aarch64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc/slurm --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-pmix=/opt/atse/pmix

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

2.2.3 release candidate 1

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

Built from source, based on OpenHPC recipes.

### Please describe the system on which you are running

Dual socket ThunderX2 aarch64 server running RedHat 7.6

-----------------------------

## Details of the problem

When launching multiple processes on the same node using mpirun, seeing the PMIX ERROR below.  This error only shows up for non-MPI programs (hostname in this case) and does not seem to show up when launching MPI processes.  The error does not happen when using srun, and did not occur using the previous PMIX 2.2.1 release.  Here is an example:

```
$ mpirun -np 2 hostname
myhost
[myhost:100305] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113
myhost
[myhost:100305] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113
 
$ srun -n 2 hostname
myhost
myhost
```

**Comment by rhc54** [comment]
Sorry for delay - just got back from vacation. There are some patches still missing from the v2.2.3 release candidate as we had turned our priorities toward the v3.1.4 release. I'll be coming back to it this week and will ensure this gets included.

**Comment by ktpedre** [comment]
OK, thanks Ralph.  We are using OpenMPI 3.1.4 and SLURM 17.11.12 (both configured for PMIx).  Is PMIx 3.1.x compatible with these versions of OpenMPI+SLURM?  If so, maybe we should switch to it.  We noted OpenHPC is still using PMIx 2.2.2 with OpenMPI 3.1.4, so that's why we stuck with 2.2.x.

**Comment by rhc54** [comment]
Technically, yes - but I don't know if the OMPI configure logic will correctly handle it. I know that Slurm will not, though there is an upstream commit in Slurm master to fix that problem.

**Comment by ktpedre** [comment]
OK, thanks, we'll stick to 2.2.x for now.

**Comment by rhc54** [comment]
@ktpedre I just posted a v2.2.3rc2 now that should (I'm hoping) fix these problems. Would you please give it a spin?

https://github.com/pmix/pmix/releases/tag/v2.2.3rc2

**Comment by rhc54** [comment]
This should have been fixed in v2.2.3 - please reopen if the problem persists

**Comment by ktpedre** [comment]
Thanks.  We haven’t had time to test yet, but will soon and let you know how it goes.


On Aug 15, 2019, at 5:42 PM, Ralph Castain <notifications@github.com<mailto:notifications@github.com>> wrote:


This should have been fixed in v2.2.3 - please reopen if the problem persists

**Comment by Honggang-LI** [comment]
I believe issue persists.

$ rpm -qa | grep pmix
pmix-2.2.3-1.el8.x86_64
pmix-devel-2.2.3-1.el8.x86_64

./configure --prefix=/home/test/install/openmpi-3.1.6-sys-pmix --with-pmix=external --with-libevent

./install/openmpi-3.1.6-sys-pmix/bin/mpirun uname -r
4.18.0-203.el8.x86_64
4.18.0-203.el8.x86_64
4.18.0-203.el8.x86_64
4.18.0-203.el8.x86_64
4.18.0-203.el8.x86_64
[rdma-dev-00.lab.bos.redhat.com:370051] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113
[rdma-dev-00.lab.bos.redhat.com:370051] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113
[rdma-dev-00.lab.bos.redhat.com:370051] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113
[rdma-dev-00.lab.bos.redhat.com:370051] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113
[rdma-dev-00.lab.bos.redhat.com:370051] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113
4.18.0-203.el8.x86_64
[rdma-dev-00.lab.bos.redhat.com:370051] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113

**Comment by Honggang-LI** [comment]
Confirmed it is pmix-2.2 regression issue.

[test@rdma-dev-00 openpmix (v2.2)]$ head config.log 
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by pmix configure 2.2.3rc2, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/home/test/opt/pmix-d0f3c21b --disable-static --disable-silent-rules --enable-pmix-binaries --with-tests-examples --enable-shared --enable-pmi-backward-compatibility --with-munge CFLAGS=-g

## --------- ##
## Platform. ##
[test@rdma-dev-00 openpmix (v2.2)]$ 
[test@rdma-dev-00 openpmix (v2.2)]$ ./test/simple/stability  -e /usr/bin/date 
Testing version 2.2.3rc2
Running cycle 0
Wed May 27 05:43:05 EDT 2020
[rdma-dev-00.lab.bos.redhat.com:747002] PMIX ERROR: BAD-PARAM in file base/pnet_base_fns.c at line 113
Test finished OK!

**Comment by Honggang-LI** [comment]
https://github.com/openpmix/openpmix/pull/1788 fixes this issue.
