### ISSUE TITLE
v3.1/PMIX ERROR: NOT-FOUND in file client/pmix_client_get.c at line 337

### ISSUE THREAD

**Issue by karasevb** [pmix/pmix#1412]
```bash
mpirun -n 2 --map-by node -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 ./ring_c
```
We get an error for both processes:
```bash
[node01] PMIX ERROR: NOT-FOUND in file client/pmix_client_get.c at line 334
[node02] PMIX ERROR: NOT-FOUND in file client/pmix_client_get.c at line 334
Process 1 exiting
Process 0 sending 10 to 1, tag 201 (2 processes in ring)
Process 0 sent to 1
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
Process 0 decremented value: 6
Process 0 decremented value: 5
Process 0 decremented value: 4
Process 0 decremented value: 3
Process 0 decremented value: 2
Process 0 decremented value: 1
Process 0 decremented value: 0
Process 0 exiting

```
This error does not affect execution; the application goes successfully.
The error message goes from here, where the key that it is trying to find is `key btl.tcp.4.1`: https://github.com/pmix/pmix/blob/v3.1/src/client/pmix_client_get.c#L334

`master` and other versions (except 3.1) do not show same error for this.

@rhc54 should this error really show?

**Comment by rhc54** [comment]
Looks like a piece of debug that got left in the code - probably was removed in a later commit that didn't get cherry-picked. I'll remove it.
