### ISSUE TITLE
PMIx hanging on multi-node SLURM jobs

### ISSUE THREAD

**Issue by tonycurtis** [pmix/pmix#1419]
Thank you for taking the time to submit an issue!

## Background information

PMIX has started hanging when run on multiple nodes under SLURM. Same programs work fine with PBS/Torque.

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

github master @ 910a43a5a96ef4370799c9417f7e0dd385b0eaee

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

git-clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7.5
* Computer hardware: x86_64
* Network type: ibv

-----------------------------

## Details of the problem

Jobs run as e.g.

```
$ salloc -p ... --nodes=2 --ntasks=2
```

hang, but running on a single node works.

Same programs continue to work fine with PBS/Torque or standalone.

**Comment by rhc54** [comment]
Were you running the job with "srun"? What was the executable doing wrt PMIx when it hung?

**Comment by tonycurtis** [comment]
It's through salloc followed by prte/prun.  Actually it appears to be the prte/prun combination that is the problem, as using openmpi as the launcher works

**Comment by rhc54** [comment]
Is PRRTE also at head of master? There was a bug in the "fence" operation that I fixed just the other day.

**Comment by tonycurtis** [comment]
Yep, PRRTE @ HEAD too, just re-installed too

**Comment by tonycurtis** [comment]
Same behavior on another SLURM cluster, BTW

**Comment by rhc54** [comment]
Can you check to see if the orted's are being started on the remote node? Meantime, I have another possibility in mind that I can check out.

**Comment by tonycurtis** [comment]
```shell
login2[1](~) ssh sn-nvda1 ps x
Warning: Permanently added 'sn-nvda1,10.10.0.157' (ECDSA) to the list of known hosts.
  PID TTY      STAT   TIME COMMAND
20176 ?        Sl     0:00 /gpfs/projects/ChapmanGroup/opt/prrte/git/bin/prted -pmca ess "slurm" -pmca ess_base_jobid "2939027456" -pmca ess_base_vpid "1" -pmca ess_base_num_procs "3" -pmca orte_hnp_uri "2939027456.0;tcp://10.10.1.250,129.49.83.50,10.10.5.250:39877"
20181 ?        Sl     0:00 ./a.out
20223 ?        S      0:00 sshd: arcurtis@notty
20227 ?        Rs     0:00 ps x


login2[1](~) ssh sn-nvda2 ps x
  PID TTY      STAT   TIME COMMAND
12267 ?        Sl     0:00 /gpfs/projects/ChapmanGroup/opt/prrte/git/bin/prted -pmca ess "slurm" -pmca ess_base_jobid "2939027456" -pmca ess_base_vpid "1" -pmca ess_base_num_procs "3" -pmca orte_hnp_uri "2939027456.0;tcp://10.10.1.250,129.49.83.50,10.10.5.250:39877"
12271 ?        Sl     0:00 ./a.out
12325 ?        S      0:00 sshd: arcurtis@notty
12329 ?        Rs     0:00 ps x
```

**Comment by rhc54** [comment]
Is there by chance a prted (not just prte) running on login2?

**Comment by tonycurtis** [comment]
Only via this SLURM job

```shell
login2[1](~) ps axuw | grep prted
arcurtis 139929  0.0  0.0 311648  4896 pts/39   Sl   14:04   0:00 srun --ntasks-per-node=1 --kill-on-bad-exit --ntasks=2 prted -pmca ess "slurm" -pmca ess_base_jobid "2939027456" -pmca ess_base_vpid "1" -pmca ess_base_num_procs "3" -pmca orte_hnp_uri "2939027456.0;tcp://10.10.1.250,129.49.83.50,10.10.5.250:39877"
arcurtis 139930  0.0  0.0  35944   684 pts/39   S    14:04   0:00 srun --ntasks-per-node=1 --kill-on-bad-exit --ntasks=2 prted -pmca ess "slurm" -pmca ess_base_jobid "2939027456" -pmca ess_base_vpid "1" -pmca ess_base_num_procs "3" -pmca orte_hnp_uri "2939027456.0;tcp://10.10.1.250,129.49.83.50,10.10.5.250:39877"
arcurtis 141637  0.0  0.0 112728   976 pts/17   S+   14:07   0:00 grep --color=auto prted
```

**Comment by rhc54** [comment]
?? Why are there two srun's executing for the same jobid? prte will generate one srun command, so where is the other one coming from?

**Comment by tonycurtis** [comment]
Here's the pstree output
```shell
sshd
  `-bash
      `-salloc --partition=gpu --nodes=2 --ntasks=2 --chdir=/gpfs/home/arcurtis/shmem/openshmem-examples/C oshrun ./a.out
          |-perl /gpfs/home/arcurtis/opt/osss-ucx/pmix/git/ucx/git/bin/oshrun ./a.out
          |   |-prte
          |   |   |-srun --ntasks-per-node=1 --kill-on-bad-exit --ntasks=2 prted -pmca ess "slurm" -pmca ess_base_jobid "3184459776" -pmca ess_base_vpid "1" -pmca ess_base_num_procs "3" -pmca orte_hnp_uri "3184459776.0;tcp://10.10.1.250,129.49.83.50,10.10.5.250:50744"
          |   |   |   |-srun --ntasks-per-node=1 --kill-on-bad-exit --ntasks=2 prted -pmca ess "slurm" -pmca ess_base_jobid "3184459776" -pmca ess_base_vpid "1" -pmca ess_base_num_procs "3" -pmca orte_hnp_uri "3184459776.0;tcp://10.10.1.250,129.49.83.50,10.10.5.250:50744"
          |   |   |   `-3*[{srun}]
          |   |   `-4*[{prte}]
          |   `-prun ./a.out
          |       `-3*[{prun}]
          `-{salloc}
```

**Comment by rhc54** [comment]
Afraid that doesn't make any sense to me, but I guess this used to work and so we would expect it to work now? I can check PRRTE for multi-node ops again, but it was working for me just yesterday on a Slurm machine. However, I launched it there using "salloc -N 2" and then manually started prte and prun.

**Comment by tonycurtis** [comment]
Yeah, it's been working for ages.  I tried with a different PMIx version (3.1.2) and got the same result so looks like it might be in PRRTE.

**Comment by tonycurtis** [comment]
Using OpenMPI as the launcher works fine
```shell
login2[1](~/shmem/openshmem-examples/C) sjob -n 2 -N 2 -p gpu ./a.out
+
+ salloc --partition=gpu --nodes=2 --ntasks=2 --chdir=/gpfs/home/arcurtis/shmem/openshmem-examples/C oshrun ./a.out
+

salloc: Granted job allocation 15370
oshrun:launch: look for "mpiexec"
oshrun:launch: using "/gpfs/projects/ChapmanGroup/opt/openmpi/4.0.1/bin/mpiexec"
oshrun:launch: "mpiexec ./a.out"
oshrun:launch: application in process 145540
oshrun:----------------------------------------------------------------------
sn-nvda2: Hello from PE    1 of    2
sn-nvda1: Hello from PE    0 of    2
oshrun:launch: done
salloc: Relinquishing job allocation 15370
```

**Comment by rhc54** [comment]
Okay, I'll try to replicate - may take me a bit.

**Comment by tonycurtis** [comment]
tnx

**Comment by tonycurtis** [comment]
+1
