### ISSUE TITLE
[Q]: pmix_base_async_modex - HOWTO

### ISSUE THREAD

**Issue by angainor** [pmix/pmix#1424]
Hi, Ralph,
I am a little confused about the async modex. In OpenMPI doc I read

> Setting the `pmix_base_async_modex` [...] causes the system to lookup the endpoint information for a peer only at first message. Thus, instead of collecting endpoint information for all processes, only the endpoint information for those processes this peer communicates with will be retrieved. 

Looking at the code, it seems that in some of the code paths in `ompi_mpi_init.c` no fence is executed
```
    /* If we have a non-blocking fence:
     * if we are doing an async modex, but we are collecting all
     * data, then execute the non-blocking modex in the background.
     * All calls to modex_recv will be cached until the background
     * modex completes. If collect_all_data is false, then we skip
     * the fence completely and retrieve data on-demand from the
     * source node.
     *
     * If we do not have a non-blocking fence, then we must always
     * execute the blocking fence as the system does not support
     * later data retrieval. */
    if (NULL != opal_pmix.fence_nb) {
        if (opal_pmix_base_async_modex && opal_pmix_collect_all_data) {
            /* execute the fence_nb in the background to collect
             * the data */
        } else if (!opal_pmix_base_async_modex) {
            /* we want to do the modex */
        }
        /* otherwise, we don't want to do the modex, so fall thru */
    } else if (!opal_pmix_base_async_modex || opal_pmix_collect_all_data) {
       [...]
    }
```
So if we want async modex and don't collect all data, then there is no fence. Do I understand correctly that in such case I do not need a fence at all, and a call to `PMIx_Get` will get the value for me from the source? I'm confused, because from your comment here #1404 it seems that the data isn't circulated without a fence.

Then again, I have a program, in which I set a string key, and then I `PMIx_Get` the value in any of the ranks without running the fence, so it seems to work. 

Could you explain how that works?

Thanks!

**Comment by rhc54** [comment]
When you do a fence and request that data be circulated, then we essentially perform an allgather operation. At the end, every daemon winds up with a complete copy of all the data posted by the individual procs. When a proc then requests data from some proc on a different node, the request is locally satisfied from the daemon's copy of the info.

When you don't do a fence, or if you instruct the fence not to collect data, then the data posted by each proc stays on its local daemon. When proc A requests info from proc B on a remote node, the daemon first checks to see if it has already obtained that data - if so, then it satisfies the request using that info. If not, then it looks up the location of proc B and sends a request for info to the daemon on that location. The receiving daemon returns all info posted by proc B to ensure that any further requests relating to proc B can be locally satisfied.

Thus, you don't need to perform a fence operation nor to circulate data - we will go get it for you upon first message. However, if you have a highly connected application (i.e., where each proc needs the connection info from a large number of its peers), then this method will be significantly slower than executing the full fence with data collection. Reason is that we are getting info one proc at a time using direct communication exchanges as opposed to gathering it all up using a more scalable collective algorithm.

So if you have sparsely connected apps, turning off the fence is the way to go for faster launch and wireup. If you have highly connected apps, then you probably want to leave the fence and collect data.

**Comment by angainor** [comment]
@rhc54 Thanks a lot for this explanation! all clear now..
