### ISSUE TITLE
pmix_server_message_handler() may lose return status

### ISSUE THREAD

**Issue by ariebs** [pmix/pmix#1431]
I was  trying to get Stony Brook SHMEM to work with Slurm, but found that Slurm doesn’t support the PMIx_Publish() or PMIx_Lookup() calls. It look me a while to figure this out, because PMIx_Publish() was returning rc=0, even though the dummy Slurm server function _publish_fn() was returning PMIX_ERR_NOT_SUPPORTED. (Interesting to note that the PMIx_Lookup() call did properly return PMIX_ERR_NOT_SUPPORTED.)

It appears to me that pmix_server_mesage_handler() is losing the return code, probably at the PMIX_BFROPS_PACK which is currently at line 3647 in the master version of pmix_server.c.

I found this with Slurm 18.08.7 and a release candidate of PMIx 3.1.3, gitd3ccd83, built and installed locally.

System: CentOS 7.6, x86_64 hardware, Mellanox OFED 4.5 on Mellanox ConnectX-3 IB gear.

**Comment by rhc54** [comment]
Thanks for the detailed report! It actually was a problem in the client side of the code - a silly typo. I should have this backported to the v3.x release series once the fix completes CI.
