### ISSUE TITLE
Different behavior for message and dstore in jobinfo

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix#281]
@karasevb I noticed that we handle `PMIX_MAP_BLOB` key differently for message and dstore cases:
* in [case of dstore](https://github.com/pmix/master/blob/v1.2/src/common/pmix_jobdata.c#L275:L280) we store the key for the `PMIX_RANK_WILDCARD`
* while in [case of messaging](https://github.com/pmix/master/blob/v1.2/src/common/pmix_jobdata.c#L283:L304) we split and store for individual ranks. 

This doesn't look right. Can you comment on that?

**Comment by karasevb** [comment]
@artpol84
The difference has been entered in additional commit 32c93e2 of PR #217 for fixing functionality of `PMIx_Resolve_peers`  in dstor case.
I agree, it not look right. I'm fixing it.

**Comment by artpol84** [comment]
@jjhursey I synced with @karasevb.
This is not a blocker. It needs to be fixed but I don't want this to delay 1.2.1

**Comment by jjhursey** [comment]
That sounds fine. I'll move this to `v1.2.2` - if it makes it in time fore `v1.2.1` then we can consider bring it in.

**Comment by artpol84** [comment]
@karasevb what is the status of this?

**Comment by jjhursey** [comment]
Another old one - should we close it? I'll move it to the v1.2.6 milestone since there hasn't been activity, but the door is still open for v1.2.5 if there is a fix coming.

**Comment by artpol84** [comment]
I think we can close it for now. This was mostly refactoring thing IIRC.
