### ISSUE TITLE
PMIx_Get logic refactoring in v1.2.2

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix#316]
We need to port https://github.com/pmix/master/pull/285 to v1.2 because the current version has performance bug causing double-search in dstore in case the key is missing.
I noticed that while tracking down https://github.com/open-mpi/ompi/pull/3011.
`OPAL_PMIX_LOCALITY` keys were defined only for the local procs, for all other procs it calls dstore_fetch twice:
* https://github.com/pmix/master/blob/v1.2/src/client/pmix_client_get.c#L582
* https://github.com/pmix/master/blob/v1.2/src/client/pmix_client_get.c#L600

**Comment by artpol84** [comment]
@jjhursey

**Comment by artpol84** [comment]
@karasevb please fix ASAP.

**Comment by artpol84** [comment]
@karasevb what is the status?

**Comment by rhc54** [comment]
v1.2 series is closed as we are moving people to the 2.x series
