### ISSUE TITLE
Modex occasionally misses a key, success on retry

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix#347]
Occasionally a `PMIx_Get` call will return key not found, then if you try again immediately it will find the key. This has been seen in the following locations in Open MPI `v2.x`:
 * `OPAL_PMIX_LOCAL_RANK`
    - https://github.com/open-mpi/ompi/blob/v2.x/orte/mca/ess/pmi/ess_pmi_module.c#L140-L141
 * `OPAL_PMIX_UNIV_SIZE`
    - https://github.com/open-mpi/ompi/blob/v2.x/orte/mca/ess/pmi/ess_pmi_module.c#L158-L159
 * Something happening with locality flags (`proc_flags`) which are being set from a `OPAL_PMIX_LOCALITY` seen as a mislabeled process (labeled nonlocal - default, instead of local)
   - https://github.com/open-mpi/ompi/blob/v2.x/opal/mca/btl/sm/btl_sm.c#L479-L483
   - Set here: https://github.com/open-mpi/ompi/blob/v2.x/ompi/proc/proc.c#L148

I confirmed in the first and third case if I immediately reissue the `OPAL_MODEX_RECV_VALUE(_OPTIONAL)` then I receive the correct value. For case 2 I have not been able to trigger that failure mode locally.

I'm using PMIx `v1.2` HEAD and testing with Open MPI `v2.x`. However, there has been a report that this can happen with PMIx `master` and Open MPI `master`. This happens both with and without the dstore. I suspect that this occurs in the `v1.1.x` series as well, but have not tried to independently confirm that yet.

I've tried adding some memory barriers in places where we store data in one thread/process and read it in another. Those have not helped.

**Comment by rhc54** [comment]
Ah, very good indeed! Thanks!

**Comment by jjhursey** [comment]
Fixed in `master` in PR #386, will be fixed in `v1.2` in PR #387 - at which point this ticket will close.

**Comment by jjhursey** [comment]
Fixed in master in PR #386 (also in v2.0), and v1.2 in PR #387. Will be in upcoming release of both branches.
