### ISSUE TITLE
munge auto-detect

### ISSUE THREAD

**Issue by gh-javier** [pmix/pmix#413]
Thanks for the software. I was recompiling Open-MPI 2.1.1 on a cluster with Torque (and munge) installed and I noticed that Open-MPI auto-detects munge, but PMIx doesn't.
<pre>
    ./configure
    ...
    *** Configuring MCA for <b>opal</b>
    checking for frameworks for opal... common, allocator, backtrace, btl, dl, event, hwloc,
    if, installdirs, memchecker, memcpy, memory, mpool, patcher, <b>pmix</b>, pstat, rcache, <b>sec</b>,
    shmem, timer
    ...
    +++ Configuring MCA framework <b>pmix</b>
    checking for no configure components in framework pmix...
    checking for m4 configure components in framework pmix... cray, s2, external, s, <b>pmix112</b>
    ...
    --- MCA component <b>pmix:pmix112</b> (m4 configuration macro)
    checking for MCA component pmix:pmix112 compile mode... dso
    checking if PMIx shared memory data store is enabled... yes
    configure: OPAL configuring in opal/mca/pmix/pmix112/pmix
    <b>configure: running /bin/sh './configure' --disable-debug ...</b>
    ...
    ============================================================================
    == Configuring PMIx
    ============================================================================
    checking build system type... x86_64-unknown-linux-gnu
    ...
    ============================================================================
    == Munge
    ============================================================================
    <b>checking will munge support be built... no</b>
    ...
    ...
    +++ Configuring MCA framework <b>sec</b>
    checking for no configure components in framework sec... basic
    checking for m4 configure components in framework sec... <b>munge</b>, keystone
    
    --- MCA component sec:basic (no configuration)
    checking for MCA component sec:basic compile mode... dso
    checking if MCA component sec:basic can compile... yes
    
    --- MCA component <b>sec:munge</b> (m4 configuration macro)
    checking for MCA component sec:munge compile mode... dso
    checking for munge in... (default search paths)
    checking munge.h usability... yes
    checking munge.h presence... yes
    checking for munge.h... yes
    looking for library without search path
    checking for library containing munge_encode... -lmunge
    checking will munge support be built... yes
    <b>checking if MCA component sec:munge can compile... yes</b>
    
    --- MCA component sec:keystone (m4 configuration macro)
    checking for MCA component sec:keystone compile mode... dso
    checking want keystone security... no
    checking if MCA component sec:keystone can compile... no
    ...
</pre>
Of course --with-munge can be forced from the command-line
<pre>
    ./configure <b>--with-munge</b>
    ...
    --- MCA component <b>pmix:pmix112</b> (m4 configuration macro)
    checking for MCA component pmix:pmix112 compile mode... dso
    checking if PMIx shared memory data store is enabled... yes
    configure: OPAL configuring in opal/mca/pmix/pmix112/pmix
    <b>configure: running /bin/sh './configure' --disable-debug ...  
    '--with-munge' ...</b>
    ...
    ============================================================================
    == Munge
    ============================================================================
    checking for munge in... (default search paths)
    checking munge.h usability... yes
    checking munge.h presence... yes
    checking for munge.h... yes
    looking for library without search path
    checking for munge_encode in -lmunge... yes
    <b>checking will munge support be built... yes</b>
</pre>
Is that the intended behavior or should PMIx also auto-detect munge?

I also found a typo (missing #) in the top-dir VERSION lines 7-8
    
    # Copyright (c) 2017      Los Alamos National Security, LLC.  All rights
                              reserved.
which appears in the log as
    
    ./VERSION: line 8: reserved.: command not found

Again, thanks for the software

**Comment by rhc54** [comment]
We debated in the community about auto-detecting munge, and eventually decided not to do so. Some of the resource managers objected because munge happened to be installed, and suddenly they found themselves using it without intending to do so.

I'm actually surprised OMPI is doing so - I suspect it was introduced in the opal/sec framework which has since been removed.

I'll fix that typo - thanks for letting us know! I'm surprised it slipped thru all the testing both here and in OMPI.

Also - thanks for the "thanks"! Glad the software is of use.

**Comment by rhc54** [comment]
I've alerted the OMPI folks about the VERSION issue - thanks again!

**Comment by Flamefire** [comment]
@rhc54 
> We debated in the community about auto-detecting munge, and eventually decided not to do so. Some of the resource managers objected because munge happened to be installed, and suddenly they found themselves using it without intending to do so.

It seems this has changed in PMIx 5.0 with 385308035914a2f01cca5c1cd0df57bf547fcc94
Now using munge is auto-enabled by default (if found) which did surprise us.
What changed that decision?

**Comment by rhc54** [comment]
> [@rhc54](https://github.com/rhc54)
> 
> > We debated in the community about auto-detecting munge, and eventually decided not to do so. Some of the resource managers objected because munge happened to be installed, and suddenly they found themselves using it without intending to do so.
> 
> It seems this has changed in PMIx 5.0 with [3853080](https://github.com/openpmix/openpmix/commit/385308035914a2f01cca5c1cd0df57bf547fcc94) Now using munge is auto-enabled by default (if found) which did surprise us. What changed that decision?

Nothing - it is an inadvertent impact from a broad-level rewrite of some m4 code in a submodule we consume from another project. I'll look into modifying the specific munge configure.m4 to restore the prior behavior.

**Comment by rhc54** [comment]
Fixed in https://github.com/openpmix/openpmix/pull/4232
