### ISSUE TITLE
gcc builtin acquire/release do not work as expected

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix#425]
I'm observing similar to https://github.com/pmix/pmix/issues/347 behavior on my x86_64 linux machine.
The reason seems to be that gcc builtins was selected as atomic implementation. In this case following functionality is used to ensure that memory is in sync state:
https://github.com/pmix/pmix/blob/master/src/atomics/sys/gcc_builtin/atomic.h#L55:L63

According to the documentation (https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html):
```
... C++11 memory model, fences (e.g., ‘__atomic_thread_fence’) take effect in combination with 
other atomic operations on specific memory locations (e.g., atomic loads); operations on specific
memory locations do not necessarily affect other operations in the same way...
```

So `__atomic_thread_fence` may not work if memory access is not performed using gcc atomic primitives.
To check that I did the following experiment:

try.c
```C
#include <stdio.h>

void pmix_atomic_rmb(void)
{
    __atomic_thread_fence (__ATOMIC_ACQUIRE);
}

void pmix_atomic_wmb(void)
{
    __atomic_thread_fence (__ATOMIC_RELEASE);
}

int pmix_atomic_cmpset_rel_32(volatile int *addr,
                                             int oldval, int newval)
{
    return __atomic_compare_exchange_n (addr, &oldval, newval, 0,
                                        __ATOMIC_RELEASE, __ATOMIC_RELAXED);
}
```
```
gcc -O3 -S try.c -o try.s
$ cat try.s 
```
```asm
	.file	"try.c"
	.text
	.p2align 4,,15
	.globl	pmix_atomic_rmb
	.type	pmix_atomic_rmb, @function
pmix_atomic_rmb:
.LFB24:
	.cfi_startproc
	rep ret
	.cfi_endproc
.LFE24:
	.size	pmix_atomic_rmb, .-pmix_atomic_rmb
	.p2align 4,,15
	.globl	pmix_atomic_wmb
	.type	pmix_atomic_wmb, @function
pmix_atomic_wmb:
.LFB25:
	.cfi_startproc
	rep ret
	.cfi_endproc
.LFE25:
	.size	pmix_atomic_wmb, .-pmix_atomic_wmb
	.p2align 4,,15
	.globl	pmix_atomic_cmpset_rel_32
	.type	pmix_atomic_cmpset_rel_32, @function
pmix_atomic_cmpset_rel_32:
.LFB26:
	.cfi_startproc
	movl	%esi, %eax
	movl	%esi, -4(%rsp)
	lock cmpxchgl	%edx, (%rdi)
	sete	%al
	movzbl	%al, %eax
	ret
	.cfi_endproc
```

So it seems that at least on x86_64 these primitives are translated to no-ops and they cannot be used to sync the memory.

**Comment by rhc54** [comment]
Probably worth reporting this as an OMPI issue as the atomics in PMIx are simply a copy of the ones developed over there.

**Comment by artpol84** [comment]
Yes, I'm going to do that.
But I want to double-check first that this is a root cause - I replaced mentioned gcc barriers with x86_64 implementation and restarted the test. It takes up to 7K iterations to reproduce.

**Comment by artpol84** [comment]
I spoke too soon. On x86_64 pthread barrier has the same effect as
```C
__asm__ __volatile__("": : :"memory")
```
This instruction also turns to noop but it instructs compiler not to do instruction reordering. The same effect comes from pthread primitives.
My mistake with the experiment above was that I considered those primitives without any context around them. I tried with 2-threaded application and compared ASM codes for no-op, asm and pthread constructions and latter two they are effectively the same, while the first one has instruction reordering that will lead to an incorrect result.

I found that `pmix_client` that was reproducing the problem uses both `PMIx_Get` and `PMIx_Get_nb`. And while the first one uses properly ordered flows, the callback for the second one is not equipped with memory barrier which caused problems.

Although I believe I saw the error appearing with `PMIx_Get` I cannot reproduce it anymore. So it might be some misunderstanding from my side.

**Comment by artpol84** [comment]
I've fixed the test suite in #422. And PR'd to other branches. I'll close this issue once they are merged.

**Comment by artpol84** [comment]
One thing is still concerning - the disclaimer at gcc builtins saying that this is not guaranteed to work with non-atomic operations.

**Comment by artpol84** [comment]
Also it may make sense to unify the part that deals with memory barrier things and not expose it to user to avoid problems. `PMIX_WAIT_FOR_COMPLETION` already considers this aspect but it is not right to rely on user to structure his callback to match `PMIX_WAIT_FOR_COMPLETION`.

**Comment by rhc54** [comment]
We definitely should do that - let's talk this week about what needs to be done. Also, let's chat with Nathan at the meeting about the disclaimer.

**Comment by artpol84** [comment]
Sounds good!

**Comment by rhc54** [comment]
rats - did you get a chance to discuss this with @hjelmn ? Is this a problem in OMPI as well?
