### ISSUE TITLE
PMIx v2.0.1 is not compatible with PMIx v2.1 - and probably not v2.0.0 either

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix#478]
We have a handshake issue during client-server connect where values are being sent/recvd in different order between the two versions. We also have issues between the pack/unpack routines due to a change in definition of pmix_data_type_t, values of pmix_cmd_t, and possibly a few other places.

The problem is that PMIx v2.0 is really PMIx v1.2 with a few new APIs and the ptl/tcp component. Thus, many of the type and value definitions are based on PMIx v1.2 and differ from those in PMIx v2.1.

We'll need to decide how we want to handle this in terms of a release strategy, but dealing with it will at least include:

* revising the v2.1 connection handshake to avoid the conflict with v2.0

* using the pmix1.2 bfrops support for v2.0

Other things are likely going to be required, and so it is probably prudent to delay release of v2.0.1 until we are sure that whatever we do for cross-version support of v2.0.1 is compatible with v2.0.0 less we create even more of a mess.

We also need to start testing cross-versions so we pickup these problems a little earlier. It can simply be done by building both versions, and then running test/simple/simptest in one with the ```-e``` option to specify the simpclient executable from the other version.

**Comment by rhc54** [comment]
I have confirmed that 2.0.0 and the current 2.0.1 are not binary compatible (160993 is the server):
```
pmix/v2.0/test/simple$ ./simptest -n 2 -e /home/common/pmix/v2.0.0/test/simple/.libs/simpclient
...
[rhc001:160993] PMIX bfrop:unpack: got type 14 when expecting type 34
[rhc001:160993] PMIX ERROR: PACK-MISMATCH in file server/pmix_server.c at line 2314
...
[rhc001:161010] PMIX bfrop:unpack: got type 20 when expecting type 3
[rhc001:161010] PMIX ERROR: PACK-MISMATCH in file client/pmix_client.c at line 197
...
[rhc001:160993] PMIX bfrop:unpack: got type 14 when expecting type 34
[rhc001:160993] PMIX ERROR: PACK-MISMATCH in file server/pmix_server.c at line 2314
...
[rhc001:161009] PMIX bfrop:unpack: got type 20 when expecting type 3
[rhc001:161009] PMIX ERROR: PACK-MISMATCH in file client/pmix_client.c at line 197
```

**Comment by rhc54** [comment]
Correction: the current head of 2.0.1 is binary compatible with 2.0.0. PR #477 breaks that compatibility, but makes 2.0.1 more compatible with 2.1.0.

So I think the only real path forward here is to drop #477, leave 2.0.1 as-is, and then deal with that problem in the 2.1.0 cross-version support. We may also want to rename 2.1.0 as 3.0 since it represents a break in ABI (even though the API might not change).

**Comment by jjhursey** [comment]
We should talk through this on the teleconf just to make sure we are all on the same page.

I agree with your last comment.
 * Leave 2.0.1 as-is and binary compatible with 2.0.0. Good for bug fix release.
 * Take #477 into 2.1.0 with the necessary handshake for cross version support.
 * According to our versioning guidelines this would still be a `2.1.0` and not a `3.0` since it does not change the API - so a re-link is all that is needed (unless statically built).

I started a wiki page [PMIx Versioning](https://github.com/pmix/pmix/wiki/PMIx-Versioning) that we can use to describe our versioning logic.

**Comment by rhc54** [comment]
Cross-version support (minus dstore) is now committed.
