### ISSUE TITLE
rpmbuild --rebuild fails

### ISSUE THREAD

**Issue by angainor** [pmix/pmix#500]
Sorry, if that is naive/redundant - I'm not a RedHat expert, and I haven't found any posts describing this problem with PMIx. I can't build RPMs on CentOS Linux release 7.3.1611 (Core):

`rpmbuild --rebuild pmix-2.0.1-1.src.rpm`
`[...]`
`File not found: /nird/home/marcink/rpmbuild/BUILDROOT/pmix-2.0.1-1.x86_64/etc`

Adding creation of /etc to the spec file helped, i.e., the RPMs have been created:

`   %{__make} install DESTDIR=$RPM_BUILD_ROOT %{?mflags_install}`
`+ %{__mkdir_p} $RPM_BUILD_ROOT/etc`

The same happens for an earlier 1.2.3 version. Do I do sth wrong, or is this a bug?

Thanks!

Marcin Krotkiewski

**Comment by rhc54** [comment]
I'm no rpm expert either, but I do believe this is likely a bug. Let me poke a bit

**Comment by rhc54** [comment]
@angainor Could you please try the referenced PR and see if I captured this correctly?

**Comment by angainor** [comment]
Ralph, thanks for a quick answer! I've looked into this a bit more. With the change I've posted the rpm builds, but there is another problem. The archive 'provides' the following directories, in addition the files they contain:
```
/usr/include/
/usr/lib64/
/usr/share/
```
Those are basic system paths, and as such are already provided by another RPM (on my system it's the `filesystem` package). In addition comes the `/etc` directory, which we 'fixed'. An attempt to Install such an RPM results in a conflict with the original RPM that provides the directories.

Again, I'm no RPM expert, but I managed to 'remove' those directories from the archive by changing the `%files` section of the spec file to the following:
```
   %files
   %defattr(-, root, root, -)
+  #%{_prefix}
+  %{_libdir}/*
+  %{_includedir}/*
+  %{_prefix}/share/*
+  # If the sysconfdir is not under the prefix, then list it explicitly.
+  #%if !%{sysconfdir_in_prefix}
+  #%{_sysconfdir}
+  #%endif

```
So, instead of adding the lacking `/etc` to the buildroot I actually removed it from the RPM by commenting out the relevant lines (this folder is empty anyways. Maybe there was content before, but now it's gone..). Also, instead of packing the entire `%{_prefix}` into the archive, I explicitly included only **contents** of the non-empty directories. This RPM contains all the files, and none of the conflicting directories. Of course, this means that my previous 'fix' should be reverted.

Please have a look - I hope that by removing the `/etc` directory I have not broken something.

Marcin

**Comment by angainor** [comment]
@rhc54 Not sure, if you got my previous report from 4 days ago. Please have a look if changes in that comment seem to make sense.
Thanks!
Marcin

**Comment by rhc54** [comment]
Sorry about that - yes, I did see your note. Afraid I've been rather busy chasing something else down and hadn't had a chance to address it.

My concern would be how this impacts install into a non-standard location where the directories don't already exist. In such a case, which isn't uncommon, we do have to make the directories. Frankly, I'm surprised that the RPM system isn't smart enough to avoid the problem.

The spec file is just a copy from the OMPI one that has been used for many years. Let me see if they have an update that we are missing.

**Comment by rhc54** [comment]
Sure enough, they updated the spec file a few months ago for exactly this problem. See #501 as I updated the spec file there.

**Comment by abouteiller** [comment]
I came to report that same bug. Are you making a release 2.0.1-2?

**Comment by rhc54** [comment]
Yes, once we get this correct and add one other bug fix
