### ISSUE TITLE
rpmbuild -ta does not work

### ISSUE THREAD

**Issue by abouteiller** [pmix/pmix#512]
Issuing `rpmbuild -ta pmix.tar.bz2` fails with an error about `$VERSION`: 

The offending lines in the .spec file are found here
`Version: $VERSION
Source: pmix-%{version}.tar.$EXTENSION`

In the source RPM, these are substituted to actual constant values, but the contrib/pmix.spec file still has these values unsubstituted.

**Comment by rhc54** [comment]
I'm not an rpm guy, so any suggestions on how to fix it would be appreciated.

**Comment by abouteiller** [comment]
pull request #515
