### ISSUE TITLE
Tag 2.0.2 is on the wrong branch?

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix#601]
@dannyauble noticed that there is some problem with tag 2.0.2.
You can see by the link below, that minor version is "1" instead of "0":
https://github.com/pmix/pmix/blob/v2.0.2/VERSION#L17

**Comment by rhc54** [comment]
huh - that is weird. have to think about that one.

**Comment by pkovacs** [comment]
Ralph, Maybe remove the v2.0.2 tag from this commit:
```
git show 3dcd5bb
commit 3dcd5bb873fb9b616abdb12846545f750ef3e3c3 (tag: v2.1.0rc1, tag: v2.0.2)
Merge: d27dbe5 87fc782
Author: Ralph Castain <rhc@open-mpi.org>
Date:   Mon Oct 16 13:08:23 2017 -0500

    Merge pull request #552 from rhc54/cmr21/rc1
    
    Add the rc1 designator
```
and add a v2.0.2 tag equal to the v2.0.2rc1 tag, just prior to the commit "Roll to v2.0.3":  
```
git show f4ff2c2
commit f4ff2c2b6781f038d2a0a949e380cc0eb792ee4d (tag: v2.0.2rc1)
Merge: 56770eb 9788a7c
Author: Ralph Castain <rhc@open-mpi.org>
Date:   Mon Oct 16 13:07:04 2017 -0500

    Merge pull request #553 from rhc54/cmr20/rc1
    
    Add the rc1 designator
```

Regards, Phil

**Comment by rhc54** [comment]
We've had multiple debates about moving existing tags in the OMPI community, and I'd rather not create the same argument here. My plan for the moment is to do nothing and just get the v2.0.3 tag correct.

**Comment by dannyauble** [comment]
Can it just be removed? I'm not sure how helpful a bad tag is.

**Comment by rhc54** [comment]
It's the same problem as moving it - people who have checked out the tag (or pulled the tags on the repo) will still have the incorrect location. Should someone then "push" tags, we wind up with the old tag again as it just overwrites.

I'm not sure the tag is all that important outside of the community itself as users and packagers just take the tarball. Frankly, I've never been all that impressed with tagging other than as a way of recovering the tarball should someone mistakenly delete it. In that rather obscure case, we can correct on the fly as the only issue here is the VERSION file itself.

**Comment by kawashima-fj** [comment]
Tags are important for developers. I sometimes type `git log TAG1..TAG2` and `git diff TAG1 TAG2`.

How about adding another tag like `v2.1.2-actual`? Open MPI had this approach.

https://github.com/open-mpi/ompi/releases/tag/v1.8.7-actual

**Comment by dannyauble** [comment]
It is your project so you can do whatever you would like, but my 2 cents on the matter is if you have a bad tag removing it should be fairly straight forward.  I am hoping you only have so many people that have push privileges, just have them also go remove the tag from their clone as well.  If you allow many people to push perhaps that is an issue.  I haven't ever experienced anything of what you are talking about in my experience (I have removed and retagged many times in Slurm).  I am guessing you have had different experiences, so this will be my last comment on the topic.

**Comment by rhc54** [comment]
It's a fair suggestion. We also have limited numbers of committers on this project. It was the OMPI folks, who have a fair number of committers, that raised the primary objections to the practice. In fairness, even the Git documentation contains strong cautions about it.

Still, I agree that getting it corrected makes sense, and that just moving the tag in this situation should be adequate. It has been done.

Thanks all for the input!
