### ISSUE TITLE
Components not found when "standard" install location used.

### ISSUE THREAD

**Issue by amckinstry** [pmix/pmix#628]
pmix fails to search for and find the MCA components when standard Debian paths are used.
i.e. for the configure line:
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infod\
ir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x8\
6_64-linux-gnu 

with components in /usr/lib/$(build)/pmix/lib/pmix/ , this directory is never searched.
If the components are in $HOME/.pmix/components then pmix tests and openmpi work fine.
Also, the same code works fine with --prefix=$(HOME)/pmix.

This is for V2.1.0rc1 and V2.1 head-of-tree.

**Comment by amckinstry** [comment]
Ok, the problem appears to be that component_path in /etc/pmi-mca-params.conf is ignored if $(LIBDIR)/pmix exists.

The layout I had in Debian is/was: prefix=/usr/lib/x86_64-linux-gnu
  $prefix/pmix
  $prefix/pmix/lib
  $prefix/pmix/include
with libpmix.so , etc in $prefix/pmix/lib and components in
 $prefix/pmix/lib/pmix

This was so that --with-pmix=$(prefix)/pmix could be used in OpenMPI  (it needs to be a directory containing the include and lib dirs), and component_path in /etc points to the components.

**Comment by rhc54** [comment]
Just to clarify: are you saying you have a param set in the pmix-mca-params.conf file, and we are ignoring it under the given condition? Can you post your .conf file?

**Comment by pkovacs** [comment]
I see the problem.   The parameter `mca_base_component_path` is initialized in `pmix_mca_base_open.c`,  but its value is not updated when you use the short name `component_path` in one of the `mca-params.conf` files.   The api `save_value()` in `pmix_mca_base_parse_paramfile.c` is not matching them.   Maybe there's a synonym problem.  

Using the longer parameter name works, so that's a workaround for now.

```
# This doesn't work
component_path = /path/to/mca/components

# This works
mca_base_component_path = /path/to/mca/components
```

**Comment by amckinstry** [comment]
I confirm this workaround works for me

**Comment by rhc54** [comment]
Hmmm...out of curiosity, what led you to the use of that shorter name? Is that something OMPI supports? I'm just asking because I'm unfamiliar with the short name for the param.

**Comment by pkovacs** [comment]
Gotta be the bottom of this file:

https://github.com/pmix/pmix/blob/master/etc/pmix-mca-params.conf

**Comment by rhc54** [comment]
Good catch! After discussing it upstream, the consensus was to fix that comment as we have (to the best of our knowledge) never actually supported a simple "component_path" name for that variable.

Sorry for the confusion!
