### ISSUE TITLE
Incorrect example "client.c"

### ISSUE THREAD

**Issue by artpol84** [pmix/pmix#648]
The issue was [originally discovered](https://groups.google.com/d/msg/pmix/p_NaCza4y_U/SciaJ4Y1AwAJ) by @stoffelj.
He was getting errors when using one of PMIx examples: https://github.com/pmix/pmix/blob/2.0.2/examples/client.c.

This example has multiple issues. The simplest one that @stoffelj hit was the fact that remote key was requested with local `myproc` process identifier:
https://github.com/pmix/pmix/blob/2.0.2/examples/client.c#L260

One more generic issue with this test is that it doesn't consider node locality. According to PMIx definition "remote" scope means that only processes on other nodes supposed to access this data, while "local" scope - vice versa - only node-local processes can access this data.

`client.c` doesn't track which rank is local and which is remote so it will provide confusing conclusions regarding correctness of PMIx implementation.

In `pmix_perf` we are using the following function to get local ranks and predict what result of PMIx_Get is expected:
https://github.com/pmix/pmix/blob/master/contrib/perf_tools/pmix.c#L48:L82
We also do this in the test suite that we are using for PMIx Jenkins:
* Get rank placement: https://github.com/pmix/pmix/blob/master/test/test_fence.c#L368
* Consider it during the check: https://github.com/pmix/pmix/blob/master/test/test_fence.c#L384:L410

I think that `client.c` should be updated to avoid future confusions.

**Comment by rhc54** [comment]
Hmmm...yeah, that code got re-used and extended well beyond its original intent (which was just a one-node smoke test). We can update it.

**Comment by artpol84** [comment]
@rhc54 Thank you.
I think that we need to backport it to release branches as people might want to use it.
Since this is not a change to the core functionality and it's a bug - should be ok.
