### ISSUE TITLE
3 * faulty compares ?

### ISSUE THREAD

**Issue by dcb314** [pmix/pmix#678]
pmi_client.c:344:17: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]
pmi2_client.c:266:17: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]
pmi2_client.c:301:17: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

**Comment by rhc54** [comment]
@artpol84 @karasevb The offending lines are in the test directory codes:
```
    if (_legacy || !_legacy) {
```
I'm not sure what the intended check was supposed to accomplish - can you take a look?

**Comment by artpol84** [comment]
@rhc54 we will.

**Comment by rhc54** [comment]
@artpol84 Any progress on this?

**Comment by artpol84** [comment]
@karasevb please have a look asap.
@rhc54, @karasevb is on vacation now, will be back next Monday, is it ok or this is urgent?

**Comment by rhc54** [comment]
sure, next week is fine - thx!

**Comment by rhc54** [comment]
Fixed by #692
