### ISSUE TITLE
PMIX_HOSTNAME missing from job data in PMIx 2.1 series

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix#704]
I'm running the simple PMIx example in the Gist below:
 * https://gist.github.com/jjhursey/b93a3c1e7d1ffe9827442d5aa114cc8e

If I run with PMIx 2.0.3 then it runs fine, but if I run with PMIx 2.1.1 (head of branch) then it fails on the `PMIx_Get(&proc, PMIX_HOSTNAME, NULL, 0, &val);` with a `-17` (`PMIX_ERR_PROC_ENTRY_NOT_FOUND`).

It seems that the job data is missing the per-process hostname in the v2.1 series. Is that expected?

**Comment by jjhursey** [comment]
Note: I thought it might be something with the `gds` component. I tried just `hash` and it gave the same behavior. If I tried just `ds12` then it failed on the 'job size' before it gets to the hostname.

**Comment by rhc54** [comment]
Where are you trying it? PMIx itself doesn't supply the value, so all this means is that whomever is acting as the server didn't set it.

**Comment by jjhursey** [comment]
Sorry I forgot that detail. I was using Open MPI v3.0.x branch (HEAD) with mpirun launch across at least 2 nodes (if I only ran one node, then it was fine).

Initially, I was trying to swap out the pmix install from pmix 2.0.3 to pmix 2.1.x (HEAD) by swapping the pmix install that LD_LIBRARY_PATH was pointing to. That highlighted the problem. I'm now trying to rebuild some fresh builds to see if that LD_LIBRARY_PATH trick was contributing to the problem.

Maybe this is an Open MPI issue. I posted here since, in my original experiment, I kept the Open MPI part constant and only changed the pmix library between the runs.

**Comment by jjhursey** [comment]
Fresh build completed.
 * Open MPI v3.0.x (HEAD) built with external PMIx 2.0 (HEAD) - works
 * Open MPI v3.0.x (HEAD) built with external PMIx 2.1 (HEAD) - fails

Nothing really special about the Open MPI build:
`./configure --prefix=/share/install/ompi-v3.0.x-dbg-v2.1 --with-libevent=/share/libevent --with-hwloc=/share/hwloc --with-pmix=/share/install/pmix-v2.1 --enable-debug`
or the PMIx build:
`./configure --prefix=/share/install/pmix-v2.1 --with-libevent=/share/libevent --disable-debug`

I can re-file a ticket with Open MPI, if you think it's on their side. I'm not sure what would have changed in the Open MPI code based upon just the PMIx minor version change though.

**Comment by rhc54** [comment]
I see. Well, it is and isn't an OMPI issue. Here is what is going on: we used to pass PMIX_HOSTNAME for every process, but that creates a giant footprint at scale. So instead ORTE passes in the ppn regex, and we use PMIx_Resolve_peer to get the hostname. This, however, means that programs which used to work by calling PMIx_Get with PMIX_HOSTNAME will now fail.

What we could do inside PMIx is try to locally retrieve PMIX_HOSTNAME, and if it fails, then try to resolve the peer and provide the answer that way. It would improve backward compatibility - might need some thought on where to do the resolve.

**Comment by jjhursey** [comment]
Using `PMIx_Resolve_peer` is a bit cumbersome since, for a given host, if gives you the peers on that host. So if you are trying to answer - "what is the hostname for rank 5?" then we would need to:
 1. Call `PMIx_Resolve_nodes` to get all of the nodes in the namespace
 2. Worst case, call `PMIx_Resolve_peer` for each node and check the resulting `procs` list.

So the workaround would be computationally expensive if we just used the PMIx API. Maybe we can optimize it a bit better if we put it deeper inside PMIx gds somewhere.

**Comment by rhc54** [comment]
ORTE provides PMIX_NODEID for each proc, so all you actually have to do is lookup the nodeid. If you truly want the string name, then we could provide some simpler way of getting it given the nodeid.

It's always going to be a tradeoff between footprint and speed.

**Comment by rhc54** [comment]
I should have said: ORTE provides the nodeid for every proc - just not the string name.

**Comment by jjhursey** [comment]
Ok. I understand that. What I still don't understand is why by just changing the external PMIx version with the same version of ORTE changes whether or not PMIX_HOSTNAME is set.

Maybe it's influencing this decision point? https://github.com/open-mpi/ompi/blob/v3.0.x/orte/orted/pmix/pmix_server_register_fns.c#L420

**Comment by rhc54** [comment]
I don't see how it could influence that decision - the cutoff value is an orte-level param, which defaults to 1000. So the hostname should be getting stored regardless of PMIx version. Since it is being directly stored, my point about resolving peers is irrelevant - we stored it, so it should be retrievable.

You might want to insert a print statement to ensure that hostname key is actually getting stored.

**Comment by jjhursey** [comment]
Yeah it looks like orted is pushing `OPAL_PMIX_HOSTNAME` into the nspace key set. I'm looking into the PMIx side now to see why it's not getting stored.

**Comment by jjhursey** [comment]
What I've found so far. It looks like the PMIx library is not packing the `PMIX_MAP_BLOB` into the job data in the v2.1 series where it was in the v2.0 series. So ORTE is doing the right thing, but the job data passed back up to it does not have the process mapping in it.

**Comment by rhc54** [comment]
Let me take a look - I assume you mean when it caches the job info vs when it retrieves and stores it upon initial client connection?

**Comment by jjhursey** [comment]
Ralph and I worked through this on the phone a bit. We think it's this like of code that's the problem:
 * https://github.com/pmix/pmix/blob/v2.1/src/mca/gds/hash/gds_hash.c#L610

Essentially we are only providing the client with the process information for the process local to it, not the information for the remote processes. So though `PMIX_HOSTNAME` is highlighted in this bug, the test would fail similarly with any remote peer specific information (e.g., `PMIX_LOCAL_RANK`).

**Comment by rhc54** [comment]
This is against 2.1:
```diff
diff --git a/src/include/pmix_globals.c b/src/include/pmix_globals.c
index 34c8635..112a331 100644
--- a/src/include/pmix_globals.c
+++ b/src/include/pmix_globals.c
@@ -55,6 +55,7 @@ PMIX_EXPORT PMIX_CLASS_INSTANCE(pmix_namelist_t,
 static void nscon(pmix_nspace_t *p)
 {
     p->nspace = NULL;
+    p->nprocs = 0;
     p->nlocalprocs = 0;
     p->all_registered = false;
     p->version_stored = false;
diff --git a/src/include/pmix_globals.h b/src/include/pmix_globals.h
index a1d4802..06992f1 100644
--- a/src/include/pmix_globals.h
+++ b/src/include/pmix_globals.h
@@ -127,6 +127,7 @@ typedef struct pmix_personality_t {
 typedef struct {
     pmix_list_item_t super;
     char *nspace;
+    pmix_rank_t nprocs;          // num procs in this nspace
     size_t nlocalprocs;
     bool all_registered;         // all local ranks have been defined
     bool version_stored;         // the version string used by this nspace has been stored
diff --git a/src/mca/gds/hash/gds_hash.c b/src/mca/gds/hash/gds_hash.c
index 95bcec0..d8611d8 100644
--- a/src/mca/gds/hash/gds_hash.c
+++ b/src/mca/gds/hash/gds_hash.c
@@ -513,6 +513,10 @@ pmix_status_t hash_cache_job_info(struct pmix_nspace_t *ns,
                 PMIX_RELEASE(kp2);
                 goto release;
             }
+            /* if this is the job size, then store it */
+            if (0 == strncmp(info[n].key, PMIX_JOB_SIZE, PMIX_MAX_KEYLEN)) {
+                nptr->nprocs = info[n].value.data.uint32;
+            }
         }
     }
 
@@ -560,7 +564,6 @@ static pmix_status_t register_info(pmix_peer_t *peer,
     pmix_hash_table_t *ht;
     pmix_value_t *val, blob;
     pmix_status_t rc = PMIX_SUCCESS;
-    pmix_rank_info_t *rinfo;
     pmix_info_t *info;
     size_t ninfo, n;
     pmix_kval_t kv;
@@ -607,9 +610,9 @@ static pmix_status_t register_info(pmix_peer_t *peer,
         PMIX_VALUE_RELEASE(val);
     }
 
-    PMIX_LIST_FOREACH(rinfo, &ns->ranks, pmix_rank_info_t) {
+    for (rank=0; rank < ns->nprocs; rank++) {
         val = NULL;
-        rc = pmix_hash_fetch(ht, rinfo->pname.rank, NULL, &val);
+        rc = pmix_hash_fetch(ht, rank, NULL, &val);
         if (PMIX_SUCCESS != rc) {
             PMIX_ERROR_LOG(rc);
             if (NULL != val) {
@@ -621,7 +624,6 @@ static pmix_status_t register_info(pmix_peer_t *peer,
             return PMIX_ERR_NOT_FOUND;
         }
         PMIX_CONSTRUCT(&buf, pmix_buffer_t);
-        rank = rinfo->pname.rank;
         PMIX_BFROPS_PACK(rc, peer, &buf, &rank, 1, PMIX_PROC_RANK);
 
         info = (pmix_info_t*)val->data.darray->array;
```

**Comment by jjhursey** [comment]
@rhc54 That patch resolved the issue for the v2.1 branch. Thanks!

I tested by accessing both `PMIX_HOSTNAME` and `PMIX_LOCAL_RANK` for the remote process. Both `PMIx_Get` calls returned the correct data.

**Comment by rhc54** [comment]
Kewl - I have a PR setup for master and will then schedule it for 2.1.2, which I guess we need to release soon.

**Comment by jjhursey** [comment]
This was fixed in PR #708 - Thanks!

**Comment by jjhursey** [comment]
I'm working with the PMIx 2.1.2 tarball right now, and I think this issue may have regressed before the release :( I'm setting up some 'cleaner' builds to confirm and work the issue. But I'm seeing the original issue again (`PMIX_LOCAL_RANK` and `PMIX_HOSTNAME` cannot be queried for a remote process).

Just a heads up. I'll keep this closed until I can verify.

**Comment by jjhursey** [comment]
Yeah I've confirmed with Open MPI v3.0.x branch and PMIx v2.1.x branch that this is still a bug. I'm not sure what regressed. I'm investigating now.

**Comment by jjhursey** [comment]
Ok I think I found the issue. It might be localized to the dstore component here:
 * https://github.com/pmix/pmix/blob/v2.1/src/mca/gds/ds12/gds_dstore.c#L3184
Which didn't get the same update that the `hash` GDS did here:
 * https://github.com/pmix/pmix/pull/708/files#diff-120611f90565f86fb27ca156587bc33cL610

**Comment by jjhursey** [comment]
I have the fix for dstore in https://github.com/pmix/pmix/pull/797
