### ISSUE TITLE
Error linking pmix_test on aarch64

### ISSUE THREAD

**Issue by rgmiller** [pmix/pmix#709]
### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)
v2.1.0

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)
Cloned the git repo, then checked out the v2.1.0 tag

### Please describe the system on which you are running

* Operating system/version: RHEL 7.4 aarch64
* Computer hardware: HPE pre-production Apache (Cavium ThunderX2 processors)
* Network type: EDR InfiniBand

-----------------------------

## Details of the problem

When trying to compile PMIx with optimizations turned on (-O1, -O2 or -O3), I get the following errors linking pmix_test:

```
CCLD     pmix_test
server_callbacks.o: In function `spawn_fn':
/ccsopen/home/xmr/git/pmix/test/server_callbacks.c:304:(.text+0xaf8): relocation truncated to fit: R_AARCH64_LDST32_ABS_LO12_NC against symbol `spawn_wait' defined in .bss section in pmix_test.o
server_callbacks.o: In function `spawn_fn':
server_callbacks.c:(.text+0xaf8): warning: One possible cause of this error is that the symbol is being referenced in the indicated code as if it had a larger alignment than was declared where it was defined.
server_callbacks.o: In function `release_cb':
server_callbacks.c:(.text+0xb6c): relocation truncated to fit: R_AARCH64_LDST32_ABS_LO12_NC against symbol `spawn_wait' defined in .bss section in pmix_test.o
server_callbacks.c:(.text+0xb6c): warning: One possible cause of this error is that the symbol is being referenced in the indicated code as if it had a larger alignment than was declared where it was defined.
server_callbacks.o: In function `_release_cb':
server_callbacks.c:(.text+0xbac): relocation truncated to fit: R_AARCH64_LDST32_ABS_LO12_NC against symbol `spawn_wait' defined in .bss section in pmix_test.o
server_callbacks.c:(.text+0xbac): warning: One possible cause of this error is that the symbol is being referenced in the indicated code as if it had a larger alignment than was declared where it was defined.
collect2: error: ld returned 1 exit status
```
I get no errors if optimizations are turned off.  The error occurs with both gcc 4.8.5 and 7.3.0, but I haven't tried any version of llvm.  It seems likely this is actually a bug in the gcc optimizer, or maybe there's some implicit assumption about alignment and/or size that's not true on aarch64.  Regardless, someone who's familiar with the PMIx code ought to take a look.

**Comment by rhc54** [comment]
Thanks for the report - this was fixed in v2.1.1
