### ISSUE TITLE
Process_monitor fails, gives PMIX_ERR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by wessle** [pmix/pmix#806]
Thank you for taking the time to submit an issue!

## Background information
While experimenting with one of the examples in pmix/examples, PMIx_Process_monitor_nb fails and returns an error.

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @ aeb383ba1ecb00515de85450abbb9e1d8e113dd8

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: IBV

-----------------------------

## Details of the problem
When using prun to run a modified version (see attached) of pmix/examples/jctrl, PMIx_Process_monitor_nb fails and changes the "active" variable to -47. According to pmix_common.h, -47 corresponds to PMIX_ERR_NOT_SUPPORTED. How do I interpret this?

[jctrl_mod.txt](https://github.com/pmix/pmix/files/2290684/jctrl_mod.txt)

**Comment by rhc54** [comment]
What version of PMIx were you building the example and PRRTE against?

**Comment by wessle** [comment]
v3.0.0, according to pmix_info in my installation directory.

**Comment by rhc54** [comment]
Oh my - it means we forgot to implement it 😧 I'll fix it and backport to the 3.0 branch.

Sorry about that! Thanks for pointing it out.

**Comment by wessle** [comment]
Okay, great, thanks!
