### ISSUE TITLE
build fails if configured --with-pmix-symbol-prefix or --enable-embedded-mod

### ISSUE THREAD

**Issue by garlick** [pmix/pmix#81]
pmix-1.1.4rc2 doesn't seem to work with these configure options.  This is on an Ubuntu 16.04 LTS system but I don't think that matters.

(Not a big deal for me but wanted to report since I stumbled over them)

Build fails when configured with `--enable-embedded-mode`

```
In file included from src/include/pmix_globals.c:19:0:
./src/include/types.h:45:27: error: #include expects "FILENAME" or <FILENAME>
[snip]
```

Build fails when configured `--with-pmix-symbol-prefix=FOO_`

```
make[2]: Entering directory '/home/garlick/proj/PMIx/pmix-1.1.4rc2/test'
  CCLD     pmi_client
pmi_client.o: In function `test_item4':
pmi_client.c:(.text+0x26): undefined reference to `PMI_Get_clique_size'
pmi_client.c:(.text+0x87): undefined reference to `PMI_Get_clique_ranks'
pmi_client.o: In function `test_item7':
[snip]
```

**Comment by rhc54** [comment]
@garlick Indeed - thanks for the report. Some first thoughts:

* --enable-embedded-mode will only work when PMIx is embedded in some other code base that is providing its own libevent. In other words, OMPI - or something like it

* --with-pmix-symbol-prefix will work just fine. However, the tests will not build unless you add --disable-visibility to the configure line, and I'd have to see how they react to the symbol hiding.

**Comment by garlick** [comment]
> --enable-embedded-mode will only work when PMIx is embedded in some other code base that is providing its own libevent. In other words, OMPI - or something like it.

I've moved to treating `libpmix.so` as an external dependency for Flux as you originally suggested and I think that's appropriate at least for early development.  Embedding PMIx in an RM seems like it might be a useful option to have down the road though.

**Comment by rhc54** [comment]
We have fixed the visibility issue for the unit tests, so I think this can be closed for now
