### ISSUE TITLE
Incomplete cleanup of dstore files

### ISSUE THREAD

**Issue by rhc54** [pmix/pmix#813]
We are seeing this in OMPI master, but it probably also occurs in prior releases. It only happens under Slurm when the ras_base_launch_orted_on_hn MCA param is set to 1 (true). When this is set, it causes mpirun to launch a daemon on the same node where mpirun is executing. The logic behind this is that the daemon and all its child processes are under Slurm - thus, they receive all Slurm-generated signals.

The problem is that we now have two PMIx servers of the same jobid running on the same node. This appears to cause conflicts during daemon and mpirun cleanup of the session directory. These conflicts are directly related to use of dstore - if I set PMIX_MCA_gds=hash, the problems go away.

The results of the conflict range from nothing to segfault of mpirun. I haven't found a reproducer that always fails, so a little fiddling will be required. Any application will trigger the problem so long as it calls PMIx_Init.

@karasevb @artpol84 Can you please take a look at this scenario? I know it isn't one we expected to encounter, but it has become standard operating procedure for LANL and I suspect others as well.

**Comment by artpol84** [comment]
@rhc54 for the first sight it seems like an OMPI problem to me. If OMPI launches additional daemon that will perform PMIx services to the clients it should disable pmix server inside mpirun.

I'd like to better understand the desired behavior. What do we want OMPI/PMIx to do?
What is the role of PMIx server inside mpirun in this case?
What is the role of PMIx server inside orted?

**Comment by rhc54** [comment]
It isn't really an OMPI problem - consider the case where someone executes two mpirun applications in parallel on the same allocation. Each mpirun will setup a server, which will conflict on their node, and will launch daemons that will likewise conflict. So it will happen any time there are more than one job sharing a node - pretty common use-case.

What we want is for each dstore to create an adequate signature to avoid stepping on each other, and to be a little more careful in its cleanup procedure so it doesn't delete someone else's memory segments. Make sense?

**Comment by artpol84** [comment]
If I recall correctly dstore uses server PID and JOB id to create a unique directory.
So I don't expect an issue with the use case you provided.

**Comment by artpol84** [comment]
Here [is the link](https://github.com/pmix/pmix/blob/ba73a784c49b5d9d0492b73940864e27c4beab9c/src/mca/common/dstore/dstore_base.c#L1786) to the code that creates directory name. PID is part of it so I don't believe that they are stepping on each other.

**Comment by rhc54** [comment]
They are stepping on each other during the _cleanup_ procedure. I suspect you are being too aggressive in removing directories and so they conflict as they are under a common session directory (since the nspace/jobid is the same in the Slurm case, and the top of the session directory is the same in the multi-mpirun case as the user is the same).

I believe you will find that it is relatively easy to reproduce using OMPI and setting the MCA param. It happens nearly every time, and the problem completely disappears if you disable the ds12 component.

**Comment by artpol84** [comment]
Ok, @karasevb will try that out.

**Comment by artpol84** [comment]
Thanks for reporting - we will try to fix ASAP

**Comment by artpol84** [comment]
BTW ds21 component is not there yet?

**Comment by rhc54** [comment]
Nope - OMPI master is on PMIx v3.0.1, not PMIx master

**Comment by rhc54** [comment]
Thanks for taking a look at this!

**Comment by karasevb** [comment]
I have tried to reproduce the problem, but all tries were unsuccessful. All the attempts are passed.

Here is details of my experiments:
- I used for test `ring_c` for 8 nodes 28 ppn. 
- Run thru the Slurm batch file: [ring_c.sbatch](https://gist.githubusercontent.com/karasevb/9c1d0ad08efba86c038c54f6f2ef1c0f/raw/f06201c6154f6bd56ab30dcf8bd98715d444f7c7/ring_c.sbatch)
- Image of processes on the first node (node05): [ps_ux.out](https://gist.githubusercontent.com/karasevb/9c1d0ad08efba86c038c54f6f2ef1c0f/raw/f06201c6154f6bd56ab30dcf8bd98715d444f7c7/ps_ux.out)
`node05` has `mpirun` and `orted` procs.
- Output file: [slurm.out](https://gist.githubusercontent.com/karasevb/9c1d0ad08efba86c038c54f6f2ef1c0f/raw/f06201c6154f6bd56ab30dcf8bd98715d444f7c7/slurm.out)
The output log shows that on the first node (node05) `dstore_finalize` is called twice for `mpirun` and `orted`, and cleanups the different dirs:
```
[node06:80610] dstore_finalize /tmp/ompi.node06.5259/jf.47944/pmix_dstor_80610
[node11:88988] dstore_finalize /tmp/ompi.node11.5259/jf.47944/pmix_dstor_88988
[node08:87084] dstore_finalize /tmp/ompi.node08.5259/jf.47944/pmix_dstor_87084
[node07:90195] dstore_finalize /tmp/ompi.node07.5259/jf.47944/pmix_dstor_90195
[node10:86547] dstore_finalize /tmp/ompi.node10.5259/jf.47944/pmix_dstor_86547
[node12:86247] dstore_finalize /tmp/ompi.node12.5259/jf.47944/pmix_dstor_86247
[node05:157359] dstore_finalize /tmp/ompi.node05.5259/jf.47944/pmix_dstor_157359
[node05:157332] dstore_finalize /tmp/ompi.node05.5259/pid.157332/pmix_dstor_157332
[node09:86248] dstore_finalize /tmp/ompi.node09.5259/jf.47944/pmix_dstor_86248
```

@rhc54 Please check. Is it similar to the conditions to get the problem you described above? What am I doing wrong?

**Comment by rhc54** [comment]
Fixed by https://github.com/open-mpi/ompi/pull/5600
