### ISSUE TITLE
inline is not correctly defined in v2.1.3

### ISSUE THREAD

**Issue by ggouaillardet** [pmix/pmix#817]
In `v2.1.3`, there are tons of warnings when building, for example

```
In file included from /home/gilles/src/pmix-v2.1/src/mca/base/pmix_mca_base_var.h:66:0,
                 from /home/gilles/src/pmix-v2.1/src/mca/gds/gds.h:21,
                 from /home/gilles/src/pmix-v2.1/src/include/pmix_globals.h:43,
                 from ../../../src/pmix-v2.1/examples/server.c:31:
/home/gilles/src/pmix-v2.1/src/class/pmix_value_array.h:67:19: warning: ‘pmix_value_array_init’ defined but not used [-Wunused-function]
 static inline int pmix_value_array_init(pmix_value_array_t *array, size_t item_sizeof)
                   ^
/home/gilles/src/pmix-v2.1/src/class/pmix_value_array.h:85:19: warning: ‘pmix_value_array_reserve’ defined but not used [-Wunused-function]
 static inline int pmix_value_array_reserve(pmix_value_array_t* array, size_t size)
                   ^
/home/gilles/src/pmix-v2.1/src/class/pmix_value_array.h:108:22: warning: ‘pmix_value_array_get_size’ defined but not used [-Wunused-function]
 static inline size_t pmix_value_array_get_size(pmix_value_array_t* array)
                      ^
/home/gilles/src/pmix-v2.1/src/class/pmix_value_array.h:161:21: warning: ‘pmix_value_array_get_item’ defined but not used [-Wunused-function]
 static inline void* pmix_value_array_get_item(pmix_value_array_t *array, size_t item_index)
                     ^
/home/gilles/src/pmix-v2.1/src/class/pmix_value_array.h:226:19: warning: ‘pmix_value_array_append_item’ defined but not used [-Wunused-function]
 static inline int pmix_value_array_append_item(pmix_value_array_t *array, const void *item)
                   ^
/home/gilles/src/pmix-v2.1/src/class/pmix_value_array.h:244:19: warning: ‘pmix_value_array_remove_item’ defined but not used [-Wunused-function]
 static inline int pmix_value_array_remove_item(pmix_value_array_t *array, size_t item_index)
```

I think the root cause is `inline` is not correctly macro-defined
From `config.status`
```
D["inline"]=" "
```

A possible fix is to backport pmix/pmix@ca510b3bf15975b848ee4b65c0565a89f085dabc

In `config.status` we end up we
```
D["inline"]=" __inline__"
```
and the warnings go away

**Comment by rhc54** [comment]
How are you getting those? I tried gcc and clang, but I can't get any warnings to appear

**Comment by ggouaillardet** [comment]
`configure --enable-debug --enable-picky`
(I also use `VPATH`, even if I am not quite sure this is relevant here)

**Comment by rhc54** [comment]
Hmmm...nope, no joy here. I configured exactly the same way and the only warning I get is:
```shell
gds_dstore.c: In function ‘dstore_del_nspace’:
gds_dstore.c:2917:38: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if((dstor_track_idx + 1) > size) {
```
This is with ```gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)```

**Comment by rhc54** [comment]
Try without VPATH and let's see if that makes the difference - I never use it myself.

**Comment by ggouaillardet** [comment]
I just tried from the `pmix-2.1.3.tar.bz2` tarball, without `VPATH` and was able to generate a lof of warnings

note I use stock `gcc`

```
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
```

the root cause is always
```
$ grep ^D..inline config.status 
D["inline"]=" "
```

I will try with other compilers from now

**Comment by ggouaillardet** [comment]
The issue does not occur with gcc `6.3.0` and `8.2.0`.

```
 $ grep ^D..inline config.status 
D["inline"]=" __inline__"
```
Though `4.8.5` is a bit old now, this is the stock compiler of CentOS 7, so I guess it is still widely used.

**Comment by rhc54** [comment]
Trying a new CentOS 7 install, I'm running into a problem in configure that complains it cannot find pthread support. How did you get around that?

**Comment by rhc54** [comment]
interesting - apparently pthread support is in the gcc-c++ package. Okay, I am now able to replicate what you saw. Why would your commit for C11 detection fix this problem?

**Comment by rhc54** [comment]
Okay, I walked thru the commit and see what is going on. Will provide a PR to update.
