### ISSUE TITLE
Question about heartbeat or other monitors

### ISSUE THREAD

**Issue by tonycurtis** [pmix/pmix#819]
Thank you for taking the time to submit an issue!

## Background information

Trying to use the heartbeat monitor, but running into problems with event handlers not being called (apparently) more than once per sending rank

### What version of the PMIx Reference Library are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @ 8429b781ba7eac704a6f7ea15c2dd684bbc33464

### Describe how PMIx was installed (e.g., from a source/distribution tarball, from a git clone, from an operating system distribution package, etc.)

clone

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: eth / ibv

-----------------------------

## Details of the problem

I have a small program adapted in part from the jctrl.c example.  I have an event handler/notification function registered for heartbeat events.  My main loop just sends heartbeats regularly until rand() sends a rank into a longer sleep.  I see the handler called exactly once per every-other-rank, and then not again.  E.g.

```shell
$ prun -n 2 ./jctrl
Client ns 711786526 rank 0: Running
Client 711786526:0 job size 2
Client ns 711786526 rank 1: Running
Client 711786526:1 job size 2
Tue Aug 21 11:49:59 2018:0: stop sending heartbeats for 8s
PMIX HEARTBEAT ALERT: rank=1 source=0 count=1                    <-- rank 1 nranks-1 triggers
Tue Aug 21 11:50:03 2018:1: stop sending heartbeats for 8s
PMIX HEARTBEAT ALERT: rank=0 source=1 count=1                    <-- rank 0 nranks-1 triggers
Tue Aug 21 11:50:07 2018:0: resume
Tue Aug 21 11:50:08 2018:0: stop sending heartbeats for 8s
Tue Aug 21 11:50:11 2018:1: resume
Tue Aug 21 11:50:14 2018:1: stop sending heartbeats for 8s
Tue Aug 21 11:50:16 2018:0: resume
Tue Aug 21 11:50:20 2018:0: stop sending heartbeats for 8s
Tue Aug 21 11:50:22 2018:1: resume
Tue Aug 21 11:50:26 2018:1: stop sending heartbeats for 8s
Tue Aug 21 11:50:28 2018:0: resume
Tue Aug 21 11:50:33 2018:0: stop sending heartbeats for 8s
```

for a bigger run, e.g. prun -n 8, I see 7 invocations on each rank, 1-per-other-sender-rank, and then no more.

I assume I am missing something in the handler to allow it to be retriggered but really not sure.  The handler's callback replies with PMIX_EVENT_ACTION_COMPLETE.

**Comment by rhc54** [comment]
I'm not entirely sure I understand the use-case here. I gather you set a heartbeat timeout less than 8 seconds, and want to see the heartbeat "alert" event every time you fail to see it? If so, I can see the problem - the heartbeat sensor code turns the monitor "off" once the client fails the timeout. I hadn't envisioned a use-case where a process would stop and then restart sending heartbeats as it typically is used to detect process hangs or failures.

If this is a use-case of interest, we could put a flag in the code so we don't keep repeating events - basically, we would turn if "off" until we receive a heartbeat again, and then turn it back "on". Should also make sure that we cleanup any monitors when a client loses connection so we don't generate a bunch off unnecessary alerts.

**Comment by tonycurtis** [comment]
I wanted to make the rank "drop off" and then come back, so was expecting the alert to be retriggered once the heartbeats started arriving again (as opposed to "one ping only" :) ).

I don't have an app as use-case but I think it might be useful if ranks could re-enlist and update other ranks that they're alive again.

**Comment by rhc54** [comment]
okay, easy enough to do - just need to finish this chapter review first.

**Comment by tonycurtis** [comment]
Great, thanks.  At least we have handlers being called, which lets us move forward with some FT things for OpenSHMEM.

**Comment by rhc54** [comment]
@tonycurtis Let me know if this works for you and I'll backport to the release branches

**Comment by tonycurtis** [comment]
Thanks, just tried it, but am not picking up alerts when heartbeats restart and then pause again.  Also getting unpack errors which might not be related?
```
$ prun -n 2 ./jctrl
Client ns 532086792 rank 0: Running
Client ns 532086792 rank 1: Running
Client 532086792:1 job size 2
Client 532086792:0 job size 2
[login:10579] PMIX ERROR: UNPACK-PAST-END in file ../../pmix-ralph/src/common/pmix_control.c at line 88
[login:10580] PMIX ERROR: UNPACK-PAST-END in file ../../pmix-ralph/src/common/pmix_control.c at line 88
[login:10579] PMIX ERROR: UNPACK-PAST-END in file ../../pmix-ralph/src/common/pmix_control.c at line 88
[login:10580] PMIX ERROR: UNPACK-PAST-END in file ../../pmix-ralph/src/common/pmix_control.c at line 88
Wed Aug 22 09:15:57 2018:0: stop sending heartbeats for 8s
Wed Aug 22 09:15:57 2018:1: stop sending heartbeats for 8s
PMIX HEARTBEAT ALERT: rank=1 source=0 count=1
PMIX HEARTBEAT ALERT: rank=0 source=1 count=1
Wed Aug 22 09:16:05 2018:0: resume
Wed Aug 22 09:16:05 2018:1: resume
[login:10579] PMIX ERROR: UNPACK-PAST-END in file ../../pmix-ralph/src/common/pmix_control.c at line 88
[login:10580] PMIX ERROR: UNPACK-PAST-END in file ../../pmix-ralph/src/common/pmix_control.c at line 88
[login:10579] PMIX ERROR: UNPACK-PAST-END in file ../../pmix-ralph/src/common/pmix_control.c at line 88
[login:10580] PMIX ERROR: UNPACK-PAST-END in file ../../pmix-ralph/src/common/pmix_control.c at line 88
```

Code's in https://bitbucket.org/tony-curtis/jctrl/src/master/ if you wanted to look.

**Comment by rhc54** [comment]
Thanks for the code - that will help. Is it okay with you if I add this code to our test suite (I'll add the Mellanox copyright headers on your behalf)? I'm trying to build it up and this would be useful.

**Comment by tonycurtis** [comment]
Sure.

**Comment by rhc54** [comment]
Hmmm...one thing catches my eye. That unpack error message is stale - the current master has an "if" statement at that line, not an error log, and protects against that case.. I don't think it is impacting the result, but it may indicate that you somehow got a stale version that might be missing other things.

I'll build and run your test code anyway.

**Comment by tonycurtis** [comment]
The PMIx is with the new comment is your repository, BTW, instead of the pmix/pmix one.

**Comment by rhc54** [comment]
Hmmm...I wonder if something in my repo got out-of-sync. Will check either way.

**Comment by rhc54** [comment]
Simple fix - forgot to remove a "return" and so we weren't restarting the timer to check beats. I wasn't getting the unpack error on pmix/pmix, so all I can guess is that my repo is somewhat stale. Will update it.

**Comment by tonycurtis** [comment]
Looks like things are "go"!
```
$ prun -n 2 ./jctrl
Client ns 1832779778 rank 0: Running
Client 1832779778:0 job size 2
Client ns 1832779778 rank 1: Running
Client 1832779778:1 job size 2
Wed Aug 22 11:28:19 2018:0: stop sending heartbeats for 8s
Wed Aug 22 11:28:20 2018:1: stop sending heartbeats for 8s
PMIX HEARTBEAT ALERT: rank=1 source=0 count=1
PMIX HEARTBEAT ALERT: rank=0 source=1 count=1
Wed Aug 22 11:28:27 2018:0: resume
Wed Aug 22 11:28:28 2018:1: resume
Wed Aug 22 11:28:31 2018:1: stop sending heartbeats for 8s
PMIX HEARTBEAT ALERT: rank=0 source=1 count=2
Wed Aug 22 11:28:37 2018:0: stop sending heartbeats for 8s
PMIX HEARTBEAT ALERT: rank=1 source=0 count=2
Wed Aug 22 11:28:39 2018:1: resume
Wed Aug 22 11:28:42 2018:1: stop sending heartbeats for 8s
```

Thanks!

**Comment by rhc54** [comment]
This appears fixed - please let me know if you hit it again.
