### ISSUE TITLE
v3.0.2 configure missing?

### ISSUE THREAD

**Issue by dhidas** [pmix/pmix#876]
I am attempting a user build.  In the release tar.gz the README and INSTALL reference ./configure, but it appears to be missing.

**Comment by rhc54** [comment]
My apologies - I forgot to post the actual release tarballs on the release link. I have done so now.

Terribly embarrassing - sorry for the trouble. Thanks for bringing it to my attention.

**Comment by dhidas** [comment]
Thanks for the quick response.  I appreciate your work.
