### ISSUE TITLE
Sync v2.2 branch with fixes from master

### ISSUE THREAD

**Issue by jjhursey** [pmix/pmix#969]
There are some bug fixes and attribute implementation that need to be backported to the v2.2 branch. I'm opening an issue so that progress on this work can be more easily tracked.

Below are the changes that should be brought over (feel free to extend), in no particular order
 * Review https://github.com/pmix/pmix/pull/954 (picks from master to v3.1)
 * https://github.com/pmix/pmix/pull/956
 * https://github.com/pmix/pmix/pull/959
 * https://github.com/pmix/pmix/pull/960
 * https://github.com/pmix/pmix/pull/949
 * https://github.com/pmix/pmix/pull/950
 * https://github.com/pmix/pmix/pull/946

An initial attempt was made in PR #965, but that needs to be re-worked from scratch to better address merge conflicts and the ordering of the full set of PRs.

**Comment by rhc54** [comment]
I think that trying to do this via cherry-pick isn't going to work. What we need to do is just work thru the master branch, identifying those things that belong in a v2.2, and then bring those across. It will be more painful in ways, but far more likely to succeed at this point.

**Comment by rhc54** [comment]
Done!
